import { createClient } from "npm:@supabase/supabase-js@2";
import JSZip from "npm:jszip@3.10.1";

const origins=new Set(["https://app.piloz.fr","http://localhost:4173","http://localhost:5173"]);
function cors(req:Request){const origin=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":origins.has(origin)?origin:"https://app.piloz.fr","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function uuid(value:unknown){const text=String(value||"");return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(text)?text:"";}
async function sha256(value:Uint8Array){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",value))].map(byte=>byte.toString(16).padStart(2,"0")).join("");}

Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{error:"Méthode non autorisée"},405);
 try{
  const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",authorization=req.headers.get("authorization")||"";if(!url||!anon||!service)throw new Error("server_not_configured");
  const userClient=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await userClient.auth.getUser();if(!user)return json(req,{error:"Authentification requise"},401);
  const body=await req.json(),batchId=uuid(body.batchId);if(!batchId)return json(req,{error:"Export invalide"},400);
  const {data:batch,error:batchError}=await userClient.from("accounting_export_batches").select("*").eq("id",batchId).maybeSingle();if(batchError||!batch)return json(req,{error:"Export introuvable"},404);if(batch.status!=="validated")return json(req,{error:"Seul un export validé peut être empaqueté"},409);
  const {data:existing}=await userClient.from("accounting_export_files").select("*").eq("export_batch_id",batch.id).eq("file_kind","attachments_zip").maybeSingle();if(existing?.storage_path){const {data:signed,error}=await admin.storage.from("company-files").createSignedUrl(existing.storage_path,300,{download:existing.file_name});if(error)throw error;return json(req,{ready:true,url:signed.signedUrl,sha256:existing.sha256,fileName:existing.file_name,reused:true});}
  const [{data:files},{data:selected}]=await Promise.all([admin.from("accounting_export_files").select("*").eq("export_batch_id",batch.id),admin.from("accounting_export_batch_entries").select("accounting_entry_id,entry_snapshot").eq("export_batch_id",batch.id)]),zip=new JSZip(),manifest:any={export_number:batch.export_number,created_at:batch.validated_at,period:{from:batch.starts_on,to:batch.ends_on},format:batch.format_key,journal_type:batch.journal_type,entry_count:batch.entry_count,piece_count:batch.piece_count,total_debit:batch.total_debit,total_credit:batch.total_credit,classification:batch.format_key==="fec_technical"?"Validation technique — revue comptable requise":"Export comptable figé",files:[],missing_attachments:[]};
  for(const file of files||[]){if(file.file_kind!=="entries"||!file.content_text)continue;zip.file(file.file_name,file.content_text);manifest.files.push({name:file.file_name,kind:file.file_kind,sha256:file.sha256,size:file.size_bytes});}
  if(batch.include_attachments){const entryIds=(selected||[]).map(row=>row.accounting_entry_id),{data:entries}=entryIds.length?await admin.from("accounting_entries").select("id,document_id,piece_reference").in("id",entryIds):{data:[]},documentIds=[...new Set((entries||[]).map(row=>row.document_id).filter(Boolean))],{data:documents}=documentIds.length?await admin.from("documents").select("id,number,final_pdf_path,final_pdf_sha256,pdf_status").in("id",documentIds):{data:[]};for(const document of documents||[]){if(document.pdf_status!=="ready"||!document.final_pdf_path){manifest.missing_attachments.push({document_id:document.id,number:document.number,reason:"final_pdf_unavailable"});continue;}const {data:file,error}=await admin.storage.from("company-files").download(document.final_pdf_path);if(error||!file){manifest.missing_attachments.push({document_id:document.id,number:document.number,reason:"download_failed"});continue;}const bytes=new Uint8Array(await file.arrayBuffer()),hash=await sha256(bytes);if(document.final_pdf_sha256&&hash!==document.final_pdf_sha256){manifest.missing_attachments.push({document_id:document.id,number:document.number,reason:"sha256_mismatch"});continue;}const name=`pieces/${String(document.number||document.id).replace(/[^a-z0-9_.-]+/gi,"_")}.pdf`;zip.file(name,bytes);manifest.files.push({name,kind:"final_pdf",sha256:hash,size:bytes.byteLength});}}
  const manifestText=JSON.stringify(manifest,null,2),manifestBytes=new TextEncoder().encode(manifestText);zip.file("manifest.json",manifestText);manifest.files.push({name:"manifest.json",kind:"manifest",sha256:await sha256(manifestBytes),size:manifestBytes.byteLength});const bytes=await zip.generateAsync({type:"uint8array",compression:"DEFLATE",compressionOptions:{level:6},platform:"DOS"}),hash=await sha256(bytes),fileName=`${batch.export_number}-pieces.zip`,storagePath=`${batch.company_id}/accounting-exports/${batch.id}/${fileName}`;
  const {error:uploadError}=await admin.storage.from("company-files").upload(storagePath,bytes,{contentType:"application/zip",upsert:false});if(uploadError&&!String(uploadError.message||"").toLowerCase().includes("already exists"))throw uploadError;await admin.from("accounting_export_files").upsert({company_id:batch.company_id,export_batch_id:batch.id,file_kind:"attachments_zip",file_name:fileName,mime_type:"application/zip",storage_path:storagePath,content_text:null,sha256:hash,size_bytes:bytes.byteLength},{onConflict:"export_batch_id,file_kind"});await admin.from("accounting_export_files").upsert({company_id:batch.company_id,export_batch_id:batch.id,file_kind:"manifest",file_name:"manifest.json",mime_type:"application/json",storage_path:null,content_text:manifestText,sha256:await sha256(manifestBytes),size_bytes:manifestBytes.byteLength},{onConflict:"export_batch_id,file_kind"});const {data:signed,error:signedError}=await admin.storage.from("company-files").createSignedUrl(storagePath,300,{download:fileName});if(signedError)throw signedError;return json(req,{ready:true,url:signed.signedUrl,sha256:hash,fileName,missingAttachments:manifest.missing_attachments});
 }catch(error){console.error("[PILOZ accounting package] generation failed",{code:String((error as any)?.message||"unknown")});return json(req,{error:"Le paquet comptable n’a pas pu être généré.",code:String((error as any)?.message||"package_failed")},502);}
});
