import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders, json } from "../_shared/http.ts";
const encoder=new TextEncoder();async function hash(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Méthode non autorisée'},405);const auth=req.headers.get('authorization');if(!auth)return json({error:'Authentification requise'},401);
 const sid=Deno.env.get('TWILIO_ACCOUNT_SID'),token=Deno.env.get('TWILIO_AUTH_TOKEN'),from=Deno.env.get('TWILIO_FROM_NUMBER');if(!sid||!token||!from)return json({error:'La vérification SMS n’est pas encore configurée.'},503);
 const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,secret=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}}),{data:{user}}=await userClient.auth.getUser();if(!user)return json({error:'Session invalide'},401);
 const {companyId,phone}=await req.json(),destination=String(phone||'');if(!/^\+[1-9]\d{7,14}$/.test(destination))return json({error:'Numéro international invalide'},400);
 const admin=createClient(url,secret),{data:member}=await admin.from('company_members').select('role').eq('company_id',companyId).eq('user_id',user.id).maybeSingle();if(!member||!['owner','admin'].includes(member.role))return json({error:'Accès refusé'},403);
 const {data:recent}=await admin.from('company_contact_verifications').select('created_at').eq('company_id',companyId).eq('channel','sms').order('created_at',{ascending:false}).limit(1).maybeSingle();if(recent&&Date.now()-new Date(recent.created_at).getTime()<60_000)return json({error:'Patientez une minute avant un nouvel envoi.'},429,{"Retry-After":"60"});
 const code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0'),expires=new Date(Date.now()+10*60_000).toISOString();await admin.from('company_contact_verifications').delete().eq('company_id',companyId).eq('channel','sms').is('consumed_at',null);const {error:insertError}=await admin.from('company_contact_verifications').insert({company_id:companyId,channel:'sms',destination,token_hash:await hash(code),expires_at:expires,created_by:user.id});if(insertError)return json({error:'Impossible de préparer la vérification.'},500);
 const body=new URLSearchParams({To:destination,From:from,Body:`Votre code PILOZ est ${code}. Il expire dans 10 minutes.`}),sent=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:'Basic '+btoa(`${sid}:${token}`),'Content-Type':'application/x-www-form-urlencoded'},body});if(!sent.ok)return json({error:'Le SMS n’a pas pu être envoyé.'},502);return json({sent:true,expiresAt:expires});
});
