import { createClient, type SupabaseClient } from "npm:@supabase/supabase-js@2";

const allowedOrigins=new Set(["https://app.piloz.fr","http://localhost:4173","http://localhost:5173"]);
const oauthProviders=new Set(["google_calendar","gmail","microsoft_calendar","outlook_mail"]);
const enc=new TextEncoder(),dec=new TextDecoder();
function cors(req:Request){const origin=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":allowedOrigins.has(origin)?origin:"https://app.piloz.fr","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Vary":"Origin","Cache-Control":"no-store"};}
function json(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function b64(bytes:Uint8Array){return standardBase64(bytes).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");}
function unb64(value:string){const raw=atob(value.replaceAll("-","+").replaceAll("_","/").padEnd(Math.ceil(value.length/4)*4,"="));return Uint8Array.from(raw,c=>c.charCodeAt(0));}
async function sha(value:string){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(value)))].map(v=>v.toString(16).padStart(2,"0")).join("");}
async function key(){const secret=Deno.env.get("INTEGRATION_TOKEN_KEY")||"";if(secret.length<32)throw new Error("integration_encryption_not_configured");return crypto.subtle.importKey("raw",await crypto.subtle.digest("SHA-256",enc.encode(secret)),"AES-GCM",false,["encrypt","decrypt"]);}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),data=enc.encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(),data);return{ciphertext:b64(new Uint8Array(cipher)),iv:b64(iv)};}
async function open(ciphertext:string,iv:string){const plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await key(),unb64(ciphertext));return JSON.parse(dec.decode(plain));}
function uuid(value:unknown){const v=String(value||"");return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)?v:"";}
function appUrl(){const value=(Deno.env.get("APP_URL")||"https://app.piloz.fr").replace(/\/$/,"");return value.startsWith("https://")||value.startsWith("http://localhost:")?value:"https://app.piloz.fr";}
function callbackUrl(){return Deno.env.get("INTEGRATION_OAUTH_CALLBACK_URL")||`${Deno.env.get("SUPABASE_URL")}/functions/v1/external-integrations` ;}
function providerFamily(provider:string){return provider.startsWith("google")?"google":"microsoft";}
function providerConfig(provider:string){
 const family=providerFamily(provider),clientId=Deno.env.get(family==="google"?"GOOGLE_OAUTH_CLIENT_ID":"MICROSOFT_OAUTH_CLIENT_ID")||"",clientSecret=Deno.env.get(family==="google"?"GOOGLE_OAUTH_CLIENT_SECRET":"MICROSOFT_OAUTH_CLIENT_SECRET")||"";
 if(!clientId||!clientSecret)throw new Error(`${family}_oauth_not_configured`);
 const scopes=provider==="google_calendar"?["openid","email","profile","https://www.googleapis.com/auth/calendar.readonly","https://www.googleapis.com/auth/calendar.events"]:provider==="gmail"?["openid","email","profile","https://www.googleapis.com/auth/gmail.send"]:provider==="microsoft_calendar"?["openid","email","profile","offline_access","User.Read","Calendars.ReadWrite"]:["openid","email","profile","offline_access","User.Read","Mail.Send"];
 return{family,clientId,clientSecret,scopes};
}
async function userContext(req:Request){
 const url=Deno.env.get("SUPABASE_URL"),anon=Deno.env.get("SUPABASE_ANON_KEY"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!anon||!service)throw new Error("supabase_not_configured");
 const authorization=req.headers.get("authorization")||"",userClient=createClient(url,anon,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
 const {data:{user}}=await userClient.auth.getUser();if(!user)throw Object.assign(new Error("authentication_required"),{status:401});return{user,userClient,admin};
}
async function requireMember(userClient:SupabaseClient,userId:string,companyId:string){const {data}=await userClient.from("company_members").select("role").eq("company_id",companyId).eq("user_id",userId).maybeSingle();if(!data)throw Object.assign(new Error("forbidden"),{status:403});return data;}
async function start(req:Request,body:any){
 const {user,userClient,admin}=await userContext(req),companyId=uuid(body.companyId),provider=String(body.provider||""),connectionScope=["personal","shared","company"].includes(String(body.connectionScope||"personal"))?String(body.connectionScope||"personal"):"personal";if(!companyId||!oauthProviders.has(provider))throw Object.assign(new Error("invalid_connection_request"),{status:400});const member=await requireMember(userClient,user.id,companyId);if(connectionScope!=="personal"&&!['owner','admin'].includes(String(member.role||"")))throw Object.assign(new Error("global_connection_permission_required"),{status:403});
 const config=providerConfig(provider),state=b64(crypto.getRandomValues(new Uint8Array(32))),verifier=b64(crypto.getRandomValues(new Uint8Array(48))),challenge=b64(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(verifier))));
 const {data:connection,error:connectionError}=await admin.from("external_connections").upsert({company_id:companyId,user_id:user.id,provider,connection_scope:connectionScope,status:"pending",last_error_code:null,updated_at:new Date().toISOString(),created_by:user.id},{onConflict:"company_id,user_id,provider"}).select("id").single();if(connectionError)throw connectionError;
 const sealed=await seal({verifier});await admin.from("external_oauth_states").delete().eq("connection_id",connection.id).is("consumed_at",null);
 const {error:stateError}=await admin.from("external_oauth_states").insert({connection_id:connection.id,state_hash:await sha(state),verifier_ciphertext:sealed.ciphertext,verifier_iv:sealed.iv,return_url:`${appUrl()}/#settings/extensions`});if(stateError)throw stateError;
 const params=new URLSearchParams({client_id:config.clientId,response_type:"code",redirect_uri:callbackUrl(),scope:config.scopes.join(" "),state,code_challenge:challenge,code_challenge_method:"S256"});
 if(config.family==="google"){params.set("access_type","offline");params.set("prompt","consent");params.set("include_granted_scopes","true");return{url:`https://accounts.google.com/o/oauth2/v2/auth?${params}`,connectionId:connection.id};}
 params.set("response_mode","query");return{url:`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${params}`,connectionId:connection.id};
}
async function exchange(provider:string,code:string,verifier:string){
 const config=providerConfig(provider),params=new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,code,code_verifier:verifier,redirect_uri:callbackUrl(),grant_type:"authorization_code"});
 const endpoint=config.family==="google"?"https://oauth2.googleapis.com/token":"https://login.microsoftonline.com/common/oauth2/v2.0/token";if(config.family==="microsoft")params.set("scope",config.scopes.join(" "));
 const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:params});const result=await response.json();if(!response.ok||!result.access_token)throw new Error("oauth_token_exchange_failed");return{...result,expires_at:Date.now()+Number(result.expires_in||3600)*1000};
}
async function profile(provider:string,accessToken:string){const endpoint=providerFamily(provider)==="google"?"https://openidconnect.googleapis.com/v1/userinfo":"https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName";const response=await fetch(endpoint,{headers:{Authorization:`Bearer ${accessToken}`}});const value=await response.json();if(!response.ok)throw new Error("oauth_profile_failed");return{email:String(value.email||value.mail||value.userPrincipalName||"").toLowerCase(),name:String(value.name||value.displayName||"")};}
async function callback(req:Request){
 const url=new URL(req.url),state=url.searchParams.get("state")||"",code=url.searchParams.get("code")||"";if(!state||!code)return Response.redirect(`${appUrl()}/#settings/extensions?connection=error`,302);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,admin=createClient(supabaseUrl,service,{auth:{persistSession:false,autoRefreshToken:false}}),stateHash=await sha(state);
 const {data:oauth}=await admin.from("external_oauth_states").select("*,external_connections!inner(id,provider,company_id,user_id)").eq("state_hash",stateHash).is("consumed_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(!oauth)return Response.redirect(`${appUrl()}/#settings/extensions?connection=expired`,302);
 const verifier=(await open(oauth.verifier_ciphertext,oauth.verifier_iv)).verifier,connection=(oauth as any).external_connections,tokens=await exchange(connection.provider,code,verifier),identity=await profile(connection.provider,tokens.access_token),sealed=await seal(tokens);
 await admin.from("external_connection_secrets").upsert({connection_id:connection.id,ciphertext:sealed.ciphertext,initialization_vector:sealed.iv,key_version:"v1",expires_at:new Date(tokens.expires_at).toISOString(),refreshable:!!tokens.refresh_token,updated_at:new Date().toISOString()});
 await admin.from("external_connections").update({status:"connected",account_email:identity.email||null,display_name:identity.name||null,consent_scope:String(tokens.scope||"").split(" ").filter(Boolean),last_error_code:null,updated_at:new Date().toISOString()}).eq("id",connection.id);
 await admin.from("external_oauth_states").update({consumed_at:new Date().toISOString()}).eq("id",oauth.id);
 return Response.redirect(`${oauth.return_url}?connection=connected&provider=${encodeURIComponent(connection.provider)}`,302);
}
async function tokensFor(admin:SupabaseClient,connection:any){
 const {data:secret}=await admin.from("external_connection_secrets").select("*").eq("connection_id",connection.id).maybeSingle();if(!secret)throw new Error("connection_secret_missing");let tokens=await open(secret.ciphertext,secret.initialization_vector);
 if(Number(tokens.expires_at||0)>Date.now()+60000)return tokens;
 if(!tokens.refresh_token)throw new Error("reauthorization_required");const config=providerConfig(connection.provider),params=new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,refresh_token:tokens.refresh_token,grant_type:"refresh_token"});if(config.family==="microsoft")params.set("scope",config.scopes.join(" "));
 const endpoint=config.family==="google"?"https://oauth2.googleapis.com/token":"https://login.microsoftonline.com/common/oauth2/v2.0/token",response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:params}),fresh=await response.json();if(!response.ok||!fresh.access_token)throw new Error("reauthorization_required");tokens={...tokens,...fresh,refresh_token:fresh.refresh_token||tokens.refresh_token,expires_at:Date.now()+Number(fresh.expires_in||3600)*1000};const sealed=await seal(tokens);await admin.from("external_connection_secrets").update({ciphertext:sealed.ciphertext,initialization_vector:sealed.iv,expires_at:new Date(tokens.expires_at).toISOString(),updated_at:new Date().toISOString()}).eq("connection_id",connection.id);return tokens;
}
async function connectionFor(req:Request,body:any){const context=await userContext(req),connectionId=uuid(body.connectionId);const {data:connection}=await context.admin.from("external_connections").select("*").eq("id",connectionId).maybeSingle();if(!connection)throw Object.assign(new Error("connection_not_found"),{status:404});const member=await requireMember(context.userClient,context.user.id,connection.company_id),canManageShared=connection.connection_scope!=="personal"&&['owner','admin'].includes(String(member.role||""));if(connection.user_id!==context.user.id&&!canManageShared)throw Object.assign(new Error("connection_owned_by_another_user"),{status:403});return{...context,connection};}
async function syncCalendarCore(admin:SupabaseClient,connection:any){
 if(!["google_calendar","microsoft_calendar"].includes(connection.provider))throw new Error("calendar_connection_required");
 const tokens=await tokensFor(admin,connection),settings=connection.settings||{},calendarId=String(settings.calendar_id||"primary"),pastDays=Math.max(0,Math.min(730,Number(settings.past_days??365))),futureDays=Math.max(1,Math.min(1095,Number(settings.future_days??365))),{data:state}=await admin.from("external_sync_states").select("*").eq("connection_id",connection.id).eq("resource_type","calendar").eq("resource_id",calendarId).maybeSingle();
 let cursor="";if(state?.cursor_ciphertext&&state?.cursor_iv)cursor=(await open(state.cursor_ciphertext,state.cursor_iv)).cursor||"";
 const items:any[]=[];let nextCursor="",fullSyncRestarted=false;
 if(connection.provider==="google_calendar"){
  let pageToken="",syncToken=cursor;
  for(let page=0;page<50;page++){
   const params=new URLSearchParams({singleEvents:"true",showDeleted:"true",maxResults:"2500"});
   if(syncToken)params.set("syncToken",syncToken);else{params.set("timeMin",new Date(Date.now()-pastDays*86400000).toISOString());params.set("timeMax",new Date(Date.now()+futureDays*86400000).toISOString());}
   if(pageToken)params.set("pageToken",pageToken);
   const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?${params}`,{headers:{Authorization:`Bearer ${tokens.access_token}`}}),value=await response.json();
   if(response.status===410&&!fullSyncRestarted){fullSyncRestarted=true;syncToken="";pageToken="";items.length=0;await admin.from("external_sync_states").update({full_sync_required:true,cursor_ciphertext:null,cursor_iv:null}).eq("connection_id",connection.id).eq("resource_type","calendar").eq("resource_id",calendarId);page=-1;continue;}
   if(!response.ok)throw new Error("calendar_sync_failed");items.push(...(value.items||[]));pageToken=String(value.nextPageToken||"");nextCursor=String(value.nextSyncToken||nextCursor);if(!pageToken)break;
  }
 }else{
  let endpoint=cursor||`https://graph.microsoft.com/v1.0/me/calendarView/delta?startDateTime=${encodeURIComponent(new Date(Date.now()-pastDays*86400000).toISOString())}&endDateTime=${encodeURIComponent(new Date(Date.now()+futureDays*86400000).toISOString())}`;
  for(let page=0;endpoint&&page<100;page++){
   const response=await fetch(endpoint,{headers:{Authorization:`Bearer ${tokens.access_token}`,Prefer:'outlook.timezone="UTC"'}}),value=await response.json();if(!response.ok)throw new Error("calendar_sync_failed");items.push(...(value.value||[]));endpoint=String(value["@odata.nextLink"]||"");nextCursor=String(value["@odata.deltaLink"]||nextCursor);
  }
 }
 let imported=0,deleted=0,unchanged=0,conflicts=0;
 for(const event of items){
  const externalId=String(event.id||"");if(!externalId)continue;
  const externalVersion=String(event.etag||event.changeKey||event.updated||event.lastModifiedDateTime||""),isDeleted=event.status==="cancelled"||!!event["@removed"],privacy=event.visibility==="private"||event.sensitivity==="private"?"private":"normal",{data:link}=await admin.from("external_event_links").select("*").eq("connection_id",connection.id).eq("external_calendar_id",calendarId).eq("external_event_id",externalId).maybeSingle();
  if(isDeleted){if(link){await admin.from("external_event_links").update({deleted_at:new Date().toISOString(),last_synced_at:new Date().toISOString()}).eq("id",link.id);if(link.activity_id){const {data:activity}=await admin.from("activities").select("metadata").eq("id",link.activity_id).maybeSingle();await admin.from("activities").update({metadata:{...(activity?.metadata||{}),external_deleted:true,external_deleted_at:new Date().toISOString()}}).eq("id",link.activity_id);}deleted++;}continue;}
  if(link?.external_version&&externalVersion&&link.external_version===externalVersion){unchanged++;continue;}
  if(settings.import_events===false){unchanged++;continue;}
  const privateBusyOnly=privacy==="private"&&settings.private_mode!=="details",start=event.start?.dateTime||event.start?.date,subject=privateBusyOnly?"Occupé":String(event.summary||event.subject||"Événement agenda").slice(0,240),description=privateBusyOnly?null:String(event.description||event.bodyPreview||"").slice(0,10000),externalUpdated=Date.parse(event.updated||event.lastModifiedDateTime||"")||0;
  let activityId=link?.activity_id||null;
  if(activityId){
   const {data:activity}=await admin.from("activities").select("updated_at,metadata").eq("id",activityId).maybeSingle(),pilozUpdated=Date.parse(activity?.updated_at||"")||0,strategy=String(settings.conflict_strategy||"latest"),pilozChanged=pilozUpdated>Date.parse(link.last_synced_at||"");
   if(pilozChanged&&(strategy==="piloz"||strategy==="manual"||strategy==="latest"&&pilozUpdated>externalUpdated)){conflicts++;await admin.from("external_event_links").update({external_version:externalVersion,last_synced_at:new Date().toISOString()}).eq("id",link.id);continue;}
   await admin.from("activities").update({subject,description,scheduled_at:start,metadata:{...(activity?.metadata||{}),external_connection_id:connection.id,external_event_id:externalId,external_private:privacy==="private",external_deleted:false},updated_at:new Date().toISOString()}).eq("id",activityId);
  }else{
   const {data:activity,error}=await admin.from("activities").insert({company_id:connection.company_id,activity_type:"meeting",subject,description,scheduled_at:start,assigned_user_id:connection.user_id,metadata:{external_connection_id:connection.id,external_event_id:externalId,external_private:privacy==="private"},created_by:connection.user_id}).select("id").single();if(error)throw error;activityId=activity.id;
  }
  await admin.from("external_event_links").upsert({company_id:connection.company_id,connection_id:connection.id,activity_id:activityId,external_calendar_id:calendarId,external_event_id:externalId,external_version:externalVersion,privacy,deleted_at:null,last_synced_at:new Date().toISOString()},{onConflict:"connection_id,external_calendar_id,external_event_id"});imported++;
 }
 if(nextCursor){const sealed=await seal({cursor:nextCursor});await admin.from("external_sync_states").upsert({company_id:connection.company_id,connection_id:connection.id,resource_type:"calendar",resource_id:calendarId,cursor_ciphertext:sealed.ciphertext,cursor_iv:sealed.iv,full_sync_required:false,last_successful_sync_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"connection_id,resource_type,resource_id"});}
 await admin.from("external_connections").update({status:"connected",last_successful_sync_at:new Date().toISOString(),last_attempt_at:new Date().toISOString(),last_error_code:null}).eq("id",connection.id);return{synced:true,imported,deleted,unchanged,conflicts,fullSyncRestarted};
}
async function syncCalendar(req:Request,body:any){const {admin,connection}=await connectionFor(req,body);return syncCalendarCore(admin,connection);}

async function listCalendars(req:Request,body:any){
 const {admin,connection}=await connectionFor(req,body);if(!["google_calendar","microsoft_calendar"].includes(connection.provider))throw new Error("calendar_connection_required");const tokens=await tokensFor(admin,connection);let rows:any[]=[];
 if(connection.provider==="google_calendar"){
  const response=await fetch("https://www.googleapis.com/calendar/v3/users/me/calendarList?minAccessRole=reader&maxResults=250",{headers:{Authorization:`Bearer ${tokens.access_token}`}}),value=await response.json();if(!response.ok)throw new Error("calendar_list_failed");rows=(value.items||[]).map((item:any)=>({id:item.id,name:item.summary||item.id,primary:!!item.primary,access:item.accessRole,color:item.backgroundColor||null}));
 }else{
  const response=await fetch("https://graph.microsoft.com/v1.0/me/calendars?$select=id,name,color,canEdit,isDefaultCalendar",{headers:{Authorization:`Bearer ${tokens.access_token}`}}),value=await response.json();if(!response.ok)throw new Error("calendar_list_failed");rows=(value.value||[]).map((item:any)=>({id:item.id,name:item.name||item.id,primary:!!item.isDefaultCalendar,access:item.canEdit?"writer":"reader",color:item.color||null}));
 }
 return{calendars:rows};
}

async function saveSettings(req:Request,body:any){
 const {userClient,connection}=await connectionFor(req,body),settings=body.settings&&typeof body.settings==="object"?body.settings:{};const {data,error}=await userClient.rpc("configure_external_connection",{target_connection_id:connection.id,target_settings:settings});if(error)throw error;return{saved:true,settings:data?.settings||settings};
}

function eventPayload(activity:any,settings:any){const start=new Date(activity.scheduled_at||Date.now()),duration=Math.max(15,Number(activity.metadata?.duration_minutes||60)),end=new Date(start.getTime()+duration*60000);return{subject:String(activity.subject||"Activité Piloz").slice(0,240),description:String(activity.description||"").slice(0,10000),start:start.toISOString(),end:end.toISOString(),timezone:String(settings?.timezone||"Europe/Paris")};}
async function pushActivity(req:Request,body:any){
 const {admin,connection}=await connectionFor(req,body);if(!["google_calendar","microsoft_calendar"].includes(connection.provider)||connection.settings?.sync_mode!=="bidirectional"||connection.settings?.export_activities!==true)throw Object.assign(new Error("calendar_export_disabled"),{status:409});const activityId=uuid(body.activityId);const {data:activity}=await admin.from("activities").select("*").eq("id",activityId).eq("company_id",connection.company_id).maybeSingle();if(!activity)throw Object.assign(new Error("activity_not_found"),{status:404});const tokens=await tokensFor(admin,connection),calendarId=String(connection.settings?.calendar_id||"primary"),event=eventPayload(activity,connection.settings),{data:existing}=await admin.from("external_event_links").select("*").eq("connection_id",connection.id).eq("activity_id",activity.id).is("deleted_at",null).maybeSingle();let externalId=existing?.external_event_id||"",version="",externalUrl="";
 if(connection.provider==="google_calendar"){
  const target=externalId?`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/${encodeURIComponent(externalId)}`:`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`,response=await fetch(target,{method:externalId?"PATCH":"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({summary:event.subject,description:event.description,start:{dateTime:event.start,timeZone:event.timezone},end:{dateTime:event.end,timeZone:event.timezone},extendedProperties:{private:{piloz_activity_id:activity.id,piloz_connection_id:connection.id}}})}),value=await response.json();if(!response.ok)throw new Error("calendar_export_failed");externalId=value.id;version=value.etag||"";externalUrl=value.htmlLink||"";
 }else{
  const target=externalId?`https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(externalId)}`:"https://graph.microsoft.com/v1.0/me/events",response=await fetch(target,{method:externalId?"PATCH":"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({subject:event.subject,body:{contentType:"text",content:event.description},start:{dateTime:event.start.replace("Z",""),timeZone:"UTC"},end:{dateTime:event.end.replace("Z",""),timeZone:"UTC"},transactionId:existing?undefined:activity.id})}),value=response.status===204?{}:await response.json();if(!response.ok)throw new Error("calendar_export_failed");externalId=value.id||externalId;version=value.changeKey||"";externalUrl=value.webLink||"";
 }
 await admin.from("external_event_links").upsert({company_id:connection.company_id,connection_id:connection.id,activity_id:activity.id,external_calendar_id:calendarId,external_event_id:externalId,external_version:version,piloz_version:activity.updated_at,privacy:"normal",deleted_at:null,last_synced_at:new Date().toISOString()},{onConflict:"connection_id,external_calendar_id,external_event_id"});await admin.from("activities").update({metadata:{...(activity.metadata||{}),external_connection_id:connection.id,external_event_id:externalId,external_url:externalUrl}}).eq("id",activity.id);return{exported:true,externalId,externalUrl};
}

function webhookUrl(){return Deno.env.get("INTEGRATION_WEBHOOK_URL")||`${Deno.env.get("SUPABASE_URL")}/functions/v1/external-integrations?webhook=1`;}
async function renewWebhookCore(admin:SupabaseClient,connection:any){
 if(!["google_calendar","microsoft_calendar"].includes(connection.provider))throw new Error("calendar_connection_required");const tokens=await tokensFor(admin,connection),calendarId=String(connection.settings?.calendar_id||"primary"),now=new Date(),{data:existing}=await admin.from("external_webhook_subscriptions").select("*").eq("connection_id",connection.id).eq("resource_type","calendar").eq("resource_id",calendarId).maybeSingle();let subscriptionId="",providerResourceId:string|null=null,tokenHash=existing?.callback_token_hash||null,expiresAt="";
 if(connection.provider==="google_calendar"){
  if(existing?.external_subscription_id&&existing?.provider_resource_id)await fetch("https://www.googleapis.com/calendar/v3/channels/stop",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({id:existing.external_subscription_id,resourceId:existing.provider_resource_id})}).catch(()=>null);
  const callbackToken=b64(crypto.getRandomValues(new Uint8Array(32)));subscriptionId=crypto.randomUUID();const expiration=now.getTime()+6*86400000,response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events/watch`,{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({id:subscriptionId,type:"web_hook",address:webhookUrl(),token:callbackToken,expiration})}),value=await response.json();if(!response.ok)throw new Error("webhook_renewal_failed");providerResourceId=String(value.resourceId||"");expiresAt=new Date(Number(value.expiration||expiration)).toISOString();tokenHash=await sha(callbackToken);
 }else if(existing?.external_subscription_id&&new Date(existing.expires_at)>now){
  expiresAt=new Date(now.getTime()+2*86400000).toISOString();const response=await fetch(`https://graph.microsoft.com/v1.0/subscriptions/${encodeURIComponent(existing.external_subscription_id)}`,{method:"PATCH",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({expirationDateTime:expiresAt})});if(!response.ok)throw new Error("webhook_renewal_failed");subscriptionId=existing.external_subscription_id;
 }else{
  const clientState=b64(crypto.getRandomValues(new Uint8Array(32)));expiresAt=new Date(now.getTime()+2*86400000).toISOString();const response=await fetch("https://graph.microsoft.com/v1.0/subscriptions",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({changeType:"created,updated,deleted",notificationUrl:webhookUrl(),resource:"me/events",expirationDateTime:expiresAt,clientState})}),value=await response.json();if(!response.ok)throw new Error("webhook_renewal_failed");subscriptionId=String(value.id||"");tokenHash=await sha(clientState);
 }
 await admin.from("external_webhook_subscriptions").upsert({company_id:connection.company_id,connection_id:connection.id,provider:connection.provider,resource_type:"calendar",resource_id:calendarId,external_subscription_id:subscriptionId,provider_resource_id:providerResourceId,callback_token_hash:tokenHash,expires_at:expiresAt,status:"active",last_renewed_at:now.toISOString(),last_error_code:null,updated_at:now.toISOString()},{onConflict:"connection_id,resource_type,resource_id"});return{renewed:true,expiresAt};
}
async function renewWebhook(req:Request,body:any){const {admin,connection}=await connectionFor(req,body);return renewWebhookCore(admin,connection);}

async function adminClient(){const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)throw new Error("supabase_not_configured");return createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});}
async function recordSyncError(admin:SupabaseClient,connection:any,job:any,error:any){const code=String(error?.message||"sync_failed").slice(0,160),attempt=Number(job?.attempt_count||0)+1,next=new Date(Date.now()+Math.min(3600,Math.pow(2,attempt)*30)*1000).toISOString();await admin.from("external_sync_errors").insert({company_id:connection.company_id,connection_id:connection.id,job_id:job?.id||null,operation:job?.job_type||"sync",error_code:code,attempt,retryable:attempt<8,next_attempt_at:attempt<8?next:null});if(job?.id)await admin.from("external_sync_jobs").update({status:attempt<8?"retry":"dead_letter",attempt_count:attempt,next_attempt_at:next,last_error_code:code,completed_at:attempt<8?null:new Date().toISOString()}).eq("id",job.id);await admin.from("external_connections").update({status:code==="reauthorization_required"?"reauthorization_required":"error",last_error_code:code,last_attempt_at:new Date().toISOString()}).eq("id",connection.id);}
async function processJobs(req:Request){
 const expected=Deno.env.get("INTEGRATION_SCHEDULER_SECRET")||"",provided=req.headers.get("x-piloz-scheduler-secret")||"";if(!expected||provided!==expected)throw Object.assign(new Error("forbidden"),{status:403});const admin=await adminClient();await admin.rpc("enqueue_external_sync_maintenance",{target_now:new Date().toISOString()});const {data:jobs}=await admin.from("external_sync_jobs").select("*").in("status",["queued","retry"]).lte("next_attempt_at",new Date().toISOString()).order("created_at").limit(20);let succeeded=0,failed=0;for(const job of jobs||[]){const {data:connection}=await admin.from("external_connections").select("*").eq("id",job.connection_id).maybeSingle();if(!connection)continue;await admin.from("external_sync_jobs").update({status:"running",started_at:new Date().toISOString()}).eq("id",job.id).in("status",["queued","retry"]);try{if(job.job_type==="renew_webhook")await renewWebhookCore(admin,connection);else await syncCalendarCore(admin,connection);await admin.from("external_sync_jobs").update({status:"succeeded",attempt_count:Number(job.attempt_count||0)+1,completed_at:new Date().toISOString(),last_error_code:null}).eq("id",job.id);succeeded++;}catch(error){await recordSyncError(admin,connection,job,error);failed++;}}return{processed:(jobs||[]).length,succeeded,failed};
}

async function webhook(req:Request){
 const url=new URL(req.url),validation=url.searchParams.get("validationToken");if(validation)return new Response(validation,{status:200,headers:{"Content-Type":"text/plain; charset=utf-8","Cache-Control":"no-store"}});const admin=await adminClient(),googleChannel=req.headers.get("x-goog-channel-id");if(googleChannel){const {data:subscription}=await admin.from("external_webhook_subscriptions").select("*").eq("external_subscription_id",googleChannel).eq("provider","google_calendar").maybeSingle(),token=req.headers.get("x-goog-channel-token")||"";if(!subscription||!token||await sha(token)!==subscription.callback_token_hash)return new Response("forbidden",{status:403});await admin.from("external_webhook_subscriptions").update({last_notification_at:new Date().toISOString()}).eq("id",subscription.id);await admin.from("external_sync_jobs").insert({company_id:subscription.company_id,connection_id:subscription.connection_id,job_type:"incremental_sync",idempotency_key:`google-notification-${googleChannel}-${req.headers.get("x-goog-message-number")||crypto.randomUUID()}`,payload:{source:"google_webhook"}});return new Response("ok",{status:200});}
 const payload=await req.json().catch(()=>({})),notifications=Array.isArray(payload.value)?payload.value:[];for(const item of notifications){const {data:subscription}=await admin.from("external_webhook_subscriptions").select("*").eq("external_subscription_id",String(item.subscriptionId||"")).eq("provider","microsoft_calendar").maybeSingle();if(!subscription||!item.clientState||await sha(String(item.clientState))!==subscription.callback_token_hash)continue;await admin.from("external_webhook_subscriptions").update({last_notification_at:new Date().toISOString()}).eq("id",subscription.id);await admin.from("external_sync_jobs").insert({company_id:subscription.company_id,connection_id:subscription.connection_id,job_type:"incremental_sync",idempotency_key:`microsoft-notification-${item.subscriptionId}-${item.sequenceNumber||crypto.randomUUID()}`,payload:{source:"microsoft_webhook"}}).then(()=>null);}return new Response(null,{status:202});
}
function standardBase64(bytes:Uint8Array){let value="";for(let offset=0;offset<bytes.length;offset+=0x8000)value+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(value);}
function safeHeader(value:string){return value.replace(/[\r\n]+/g," ").trim();}
function mimeMessage(to:string[],subject:string,body:string,attachment?:{name:string;bytes:Uint8Array}){
 if(!attachment)return[`To: ${to.join(", ")}`,`Subject: ${safeHeader(subject)}`,"MIME-Version: 1.0","Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: 8bit","",body].join("\r\n");
 const boundary=`piloz-${crypto.randomUUID()}`,encoded=standardBase64(attachment.bytes).match(/.{1,76}/g)?.join("\r\n")||"";
 return[`To: ${to.join(", ")}`,`Subject: ${safeHeader(subject)}`,"MIME-Version: 1.0",`Content-Type: multipart/mixed; boundary=\"${boundary}\"`,"",`--${boundary}`,"Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: 8bit","",body,"",`--${boundary}`,`Content-Type: application/pdf; name=\"${safeHeader(attachment.name)}\"`,`Content-Disposition: attachment; filename=\"${safeHeader(attachment.name)}\"`,"Content-Transfer-Encoding: base64","",encoded,`--${boundary}--`,""].join("\r\n");
}
async function sendMail(req:Request,body:any){
 const {admin,connection,user}=await connectionFor(req,body);if(!["gmail","outlook_mail"].includes(connection.provider))throw new Error("mail_connection_required");
 const recipients:string[]=(Array.isArray(body.to)?body.to:String(body.to||"").split(/[;,]/)).map(String).map((v:string)=>v.trim().toLowerCase()).filter((v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)).slice(0,20),subject=safeHeader(String(body.subject||"")).slice(0,240),content=String(body.body||"").slice(0,100000);if(!recipients.length||!subject||!content)throw Object.assign(new Error("invalid_mail"),{status:400});
 const documentId=uuid(body.documentId),clientId=uuid(body.clientId),opportunityId=uuid(body.opportunityId);let attachment:undefined|{name:string;bytes:Uint8Array},documentRow:any=null;
 if(documentId){
  const {data:doc,error:docError}=await admin.from("documents").select("id,company_id,client_id,opportunity_id,number,document_type,final_pdf_path,final_pdf_sha256").eq("id",documentId).maybeSingle();if(docError)throw docError;if(!doc||doc.company_id!==connection.company_id)throw Object.assign(new Error("document_not_found"),{status:404});documentRow=doc;
  if(doc.final_pdf_path){
   const prefix=`${connection.company_id}/documents/${doc.id}/`;if(!String(doc.final_pdf_path).startsWith(prefix))throw Object.assign(new Error("invalid_document_path"),{status:409});
   const {data:file,error:fileError}=await admin.storage.from("company-files").download(doc.final_pdf_path);if(fileError||!file)throw Object.assign(new Error("document_pdf_unavailable"),{status:409});const bytes=new Uint8Array(await file.arrayBuffer());if(!bytes.length)throw Object.assign(new Error("document_pdf_empty"),{status:409});
   const label=doc.document_type==="quote"?"Devis":doc.document_type==="credit_note"?"Avoir":"Facture";attachment={name:`${label}-${String(doc.number||doc.id).replace(/[^a-z0-9._-]+/gi,"-")}.pdf`,bytes};
  }
 }
 const tokens=await tokensFor(admin,connection);let externalId="";
 if(connection.provider==="gmail"){
  const raw=mimeMessage(recipients,subject,content,attachment),response=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({raw:b64(enc.encode(raw))})});const value=await response.json();if(!response.ok)throw new Error("mail_send_failed");externalId=String(value.id||"");
 }else{
  const message:any={subject,body:{contentType:"Text",content},toRecipients:recipients.map((address:string)=>({emailAddress:{address}}))};if(attachment)message.attachments=[{"@odata.type":"#microsoft.graph.fileAttachment",name:attachment.name,contentType:"application/pdf",contentBytes:standardBase64(attachment.bytes)}];
  const response=await fetch("https://graph.microsoft.com/v1.0/me/sendMail",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({message,saveToSentItems:true})});if(!response.ok)throw new Error("mail_send_failed");externalId=`graph-${crypto.randomUUID()}`;
 }
 const sentAt=new Date().toISOString(),resolvedClientId=clientId||uuid(documentRow?.client_id)||null,resolvedOpportunityId=opportunityId||uuid(documentRow?.opportunity_id)||null;
 const {data:mailLink,error:mailError}=await admin.from("external_mail_links").insert({company_id:connection.company_id,connection_id:connection.id,client_id:resolvedClientId,opportunity_id:resolvedOpportunityId,document_id:documentId||null,external_message_id:externalId,direction:"outbound",sender:connection.account_email||connection.display_name||null,subject,preview:String(content||"").slice(0,300),recipients,sent_at:sentAt,status:"sent",treatment_status:"processed",assigned_user_id:user.id,created_by:user.id}).select("id").single();if(mailError)throw new Error("mail_history_failed");
 await admin.from("activities").insert({company_id:connection.company_id,client_id:resolvedClientId,opportunity_id:resolvedOpportunityId,document_id:documentId||null,activity_type:"email",subject:`E-mail envoyé — ${subject}`,description:`Message envoyé depuis ${connection.account_email||connection.display_name||connection.provider}.`,completed_at:sentAt,status:"completed",assigned_user_id:user.id,metadata:{source:connection.provider,external_message_id:externalId,external_mail_link_id:mailLink.id,recipient_count:recipients.length},created_by:user.id,updated_by:user.id});
 if(resolvedClientId)await admin.from("client_activity_events").insert({company_id:connection.company_id,client_id:resolvedClientId,event_type:"email.sent",summary:`E-mail envoyé — ${subject}`,entity_type:"external_mail_link",entity_id:mailLink.id,metadata:{document_id:documentId||null,provider:connection.provider,recipient_count:recipients.length},actor_user_id:user.id,created_by:user.id});
 return{sent:true,messageId:externalId,historyId:mailLink.id,attachmentIncluded:Boolean(attachment)};
}

Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});const requestUrl=new URL(req.url);if(requestUrl.searchParams.has("webhook")||requestUrl.searchParams.has("validationToken")){try{return await webhook(req);}catch(error){console.error("[PILOZ integrations] webhook rejected",{code:String((error as any)?.message||"unknown")});return new Response("rejected",{status:403});}}if(req.method==="GET")try{return await callback(req);}catch(error){console.error("[PILOZ integrations] callback failed",{code:String((error as any)?.message||"unknown")});return Response.redirect(`${appUrl()}/#settings/extensions?connection=error`,302);}if(req.method!=="POST")return json(req,{error:"Méthode non autorisée"},405);
 try{const body=await req.json(),action=String(body.action||"");if(action==="start")return json(req,await start(req,body));if(action==="list_calendars")return json(req,await listCalendars(req,body));if(action==="save_settings")return json(req,await saveSettings(req,body));if(action==="sync_calendar")return json(req,await syncCalendar(req,body));if(action==="push_activity")return json(req,await pushActivity(req,body));if(action==="renew_webhook")return json(req,await renewWebhook(req,body));if(action==="process_jobs")return json(req,await processJobs(req));if(action==="send_mail")return json(req,await sendMail(req,body));if(action==="disconnect"){const {admin,connection}=await connectionFor(req,body);await admin.from("external_connection_secrets").delete().eq("connection_id",connection.id);await admin.from("external_webhook_subscriptions").update({status:"stopped",updated_at:new Date().toISOString()}).eq("connection_id",connection.id);await admin.from("external_connections").update({status:"disconnected",disconnected_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",connection.id);return json(req,{disconnected:true});}if(action==="test_imap_smtp")return json(req,{error:"Le test IMAP/SMTP nécessite le connecteur réseau dédié, non configuré sur cette instance.",code:"imap_runtime_not_configured",configured:false},503);return json(req,{error:"Action inconnue"},400);}catch(error){const status=Number((error as any)?.status||500),code=String((error as any)?.message||"integration_failed");console.error("[PILOZ integrations] action failed",{code,status});return json(req,{error:code==="forbidden"?"Accès refusé.":code==="authentication_required"?"Authentification requise.":code==="connection_owned_by_another_user"?"Cette connexion appartient à un autre collaborateur.":"L’intégration n’a pas pu terminer cette action.",code},status<500?status:502);}
});
