begin;

with source(category_slug,slug,title,summary,content) as (values
('premiers-pas','prise-en-main-piloz-15-minutes','Prendre en main Piloz en 15 minutes','Le parcours le plus court pour configurer l’entreprise et réaliser un premier cycle de vente.',E'## Objectif\n\nObtenir un espace Piloz prêt à créer un client, un devis, une facture et un règlement.\n\n## Étape 1 — vérifier l’entreprise\n\nOuvrez **Paramètres > Mon entreprise**. Contrôlez la raison sociale, les adresses, les informations légales, la fiscalité, le logo et les coordonnées bancaires. Une information manquante peut bloquer la finalisation ou la facturation électronique.\n\n## Étape 2 — vérifier les ventes\n\nOuvrez **Paramètres > Ventes & Documents**. Contrôlez les séquences de numérotation, les conditions de paiement et la marge par défaut. Une séquence déjà utilisée ne doit plus être remise en arrière.\n\n## Étape 3 — créer le premier client\n\nOuvrez **Bibliothèque > Clients**, recherchez l’entreprise avec l’INPI ou saisissez-la manuellement, puis complétez le contact principal.\n\n## Étape 4 — créer le devis\n\nOuvrez **Ventes > Devis**, sélectionnez le client, ajoutez les lignes et validez après contrôle des dates, prix, TVA et conditions.\n\n## Étape 5 — facturer et encaisser\n\nConvertissez le devis en facture brouillon, contrôlez les mentions, finalisez puis enregistrez le règlement depuis la consultation.\n\n## Contrôle final\n\nLe tableau de bord doit afficher les montants réels. Le devis, la facture et le règlement doivent rester liés et accessibles dans leur historique.'),
('devis','cycle-vente-complet','Réaliser un cycle de vente complet','Du prospect au paiement : le déroulé recommandé pour conserver une piste d’audit lisible.',E'## Vue d’ensemble\n\nLe cycle recommandé est : **prospect → opportunité → client → devis → facture → règlement**. Utiliser ce chemin limite les ressaisies et conserve les liens entre les documents.\n\n## 1. Qualifier le prospect\n\nDepuis **Suivi commercial**, créez le prospect, complétez son besoin et planifiez la prochaine action.\n\n## 2. Créer l’opportunité\n\nRenseignez le montant, la probabilité, le responsable et l’étape réelle. Le pipeline doit être mis à jour après chaque activité importante.\n\n## 3. Émettre le devis\n\nCréez le devis depuis l’opportunité. Si le tiers était encore prospect, il devient client. Ajoutez les lignes, titres et conditions puis validez.\n\n## 4. Convertir en facture\n\nOuvrez le devis validé et utilisez **Convertir en… > Facture**. Piloz ouvre un brouillon relié au devis. Activez une situation uniquement si le marché doit être facturé à l’avancement.\n\n## 5. Finaliser et encaisser\n\nContrôlez la date, l’échéance, la TVA et les mentions obligatoires. Après finalisation, enregistrez chaque règlement réel. Une facture définitive se corrige par avoir, jamais par modification directe.\n\n## Résultat attendu\n\nChaque document apparaît dans les documents liés et le tableau de bord reflète les montants finalisés et encaissés.'),
('factures','checklist-avant-finalisation-facture','Checklist avant de finaliser une facture','Les contrôles essentiels à effectuer avant d’attribuer un numéro définitif.',E'## Pourquoi ce contrôle est important\n\nUne facture finalisée reçoit un numéro définitif, devient verrouillée et entre dans les exports. Prenez quelques secondes pour vérifier chaque point.\n\n## Identité et client\n\n- l’entreprise émettrice est complète ;\n- le client est sélectionné ;\n- les adresses et identifiants légaux sont corrects ;\n- les coordonnées électroniques sont présentes si le connecteur les exige.\n\n## Dates\n\n- la date de facture respecte la chronologie ;\n- la date de vente ou prestation est correcte ;\n- l’échéance correspond aux conditions convenues.\n\n## Lignes et fiscalité\n\n- désignation, quantité, unité et prix sont exacts ;\n- les remises sont rattachées aux bonnes lignes ;\n- le taux de TVA ou le motif d’exonération est cohérent ;\n- les totaux HT, TVA et TTC sont cohérents.\n\n## Paiement et mentions\n\n- le délai et le moyen de paiement sont renseignés ;\n- les pénalités et l’indemnité applicables figurent sur le document ;\n- les coordonnées bancaires apparaissent si le virement est proposé.\n\n## Après finalisation\n\nOuvrez la consultation, vérifiez le PDF définitif et utilisez un avoir si une correction est nécessaire.'),
('factures','choisir-facture-acompte-situation','Choisir entre facture classique, acompte et situation','Comprendre quel document utiliser selon le moment du contrat.',E'## Facture classique\n\nUtilisez-la pour facturer en une fois une vente ou une prestation réalisée. Elle peut être créée manuellement ou depuis un devis.\n\n## Facture d’acompte\n\nUtilisez-la lorsqu’un montant est exigé avant l’exécution complète. Si le devis prévoit un acompte, Piloz impose la facture d’acompte avant la facture suivante. L’acompte est ensuite déduit selon la méthode choisie.\n\n## Facture de situation\n\nUtilisez-la pour un marché facturé selon un avancement cumulé. Créez d’abord une facture brouillon depuis le devis, puis activez **Facture de situation** dans les paramètres de droite. Saisissez l’avancement global, par titre ou par ligne.\n\n## Situation suivante et solde\n\nDepuis la situation finalisée, créez la suivante. Les quantités contractuelles restent inchangées ; seul le pourcentage facturé évolue. À 100 %, aucune nouvelle situation ne peut être créée et le cycle se termine par le solde.\n\n## À retenir\n\nNe créez pas plusieurs documents concurrents pour le même avancement. Contrôlez le tableau récapitulatif du marché avant chaque finalisation.'),
('resolution-erreurs','resoudre-erreur-synchronisation','Résoudre une erreur de synchronisation','Les vérifications à effectuer lorsque Piloz indique Hors ligne ou qu’une sauvegarde échoue.',E'## Ne fermez pas immédiatement la page\n\nConservez le formulaire ouvert afin de ne pas perdre une saisie non enregistrée.\n\n## Vérifications rapides\n\n1. Vérifiez la connexion internet.\n2. Vérifiez que la bonne entreprise est affichée en bas du menu.\n3. Rechargez la page une seule fois si aucune saisie non enregistrée ne risque d’être perdue.\n4. Reconnectez-vous si la session a expiré.\n\n## Référence devenue invalide\n\nSi Piloz indique qu’une référence sélectionnée n’est plus valide, rechargez les listes puis sélectionnez de nouveau le client, l’article, le taux ou le moyen de paiement concerné.\n\n## Changement de compte\n\nAprès une déconnexion, Piloz doit vider les données de l’entreprise précédente avant d’afficher le nouveau compte. Si une ancienne donnée reste visible, déconnectez-vous et signalez immédiatement le cas au support.\n\n## Créer un ticket utile\n\nIndiquez la page, l’action, l’heure, le message exact et les étapes de reproduction. Ne joignez jamais de cookie, jeton, mot de passe ou clé secrète.'),
('exports-comptables','checklist-export-comptable','Contrôler un export comptable','Une checklist pour valider les comptes, l’équilibre et la période avant téléchargement.',E'## Avant la prévisualisation\n\nVérifiez les journaux, l’exercice, les comptes clients, les comptes de vente, les comptes de TVA et les comptes financiers. Chaque type de ligne facturable doit avoir un compte.\n\n## Pendant la prévisualisation\n\n- contrôlez la période et le nombre de pièces ;\n- vérifiez le compte client stable ;\n- vérifiez le regroupement des montants HT par compte de vente ;\n- vérifiez les lignes de TVA ;\n- vérifiez que le total débit égale le total crédit.\n\n## Mode client individualisé\n\nDans ce mode, **CompteNum** contient 411 suivi de l’identifiant normalisé du client. **CompAuxNum** et **CompAuxLib** restent vides. Le même client doit conserver le même compte.\n\n## Blocages normaux\n\nPiloz bloque l’export si un compte manque, si une pièce est déséquilibrée ou si aucune donnée ne correspond à la période. Corrigez le paramétrage avant de relancer.\n\n## Après téléchargement\n\nConservez le fichier exporté et contrôlez le résultat de son import dans le logiciel comptable.'),
('utilisateurs-roles','securiser-equipe-et-droits','Sécuriser les rôles de l’équipe','Attribuer les bons accès sans exposer les données ou fonctions sensibles.',E'## Principe du moindre privilège\n\nChaque utilisateur doit recevoir uniquement les droits nécessaires à son travail. Commencez par un rôle limité puis ajoutez les permissions justifiées.\n\n## Rôles sensibles\n\nRéservez la gestion de l’entreprise, des utilisateurs, des abonnements, des modèles, de la comptabilité et des exports aux personnes autorisées.\n\n## Contrôles recommandés\n\n- vérifiez régulièrement les utilisateurs actifs ;\n- retirez rapidement les accès d’une personne partie ;\n- activez le MFA ;\n- ne partagez jamais un compte entre plusieurs personnes ;\n- testez un rôle avant de l’attribuer largement.\n\n## Traçabilité\n\nLes actions sensibles doivent être réalisées avec le compte nominatif de leur auteur. Un administrateur ne doit jamais demander le mot de passe ou le code MFA d’un utilisateur.'),
('facturation-electronique','comprendre-statuts-facture-electronique','Comprendre les statuts d’une facture électronique','Lire les retours de la plateforme et agir sans simuler un envoi réussi.',E'## Principe\n\nUne facture électronique suit plusieurs états entre sa préparation, sa transmission, sa réception et son traitement. Piloz affiche uniquement un statut confirmé par le connecteur.\n\n## Avant envoi\n\nLe document doit être finalisé et les données vendeur, acheteur, lignes, TVA, totaux et identifiants électroniques doivent être complètes.\n\n## Après transmission\n\nConsultez l’historique pour connaître le résultat réel. Un rejet technique ou métier doit conserver son motif. Corrigez la cause dans un document autorisé ou suivez la procédure d’avoir lorsqu’une facture définitive doit être rectifiée.\n\n## Factures fournisseurs\n\nUne facture reçue peut être approuvée, mise en litige, suspendue ou refusée selon les règles disponibles. Les statuts qui exigent un motif ne doivent jamais être envoyés sans celui-ci.\n\n## À retenir\n\nUn bouton cliqué ne prouve pas un envoi réussi. Seul le retour accepté de la plateforme fait foi dans Piloz.')
), prepared as (
 select category.id category_id,source.* from source
 join public.knowledge_categories category on category.slug=source.category_slug
), upserted as (
 insert into public.knowledge_articles(category_id,slug,title,summary,content,status,visibility,availability,current_version,published_at,last_reviewed_at)
 select category_id,slug,title,summary,content,'published','authenticated','available',1,now(),now() from prepared
 on conflict(slug) do update set category_id=excluded.category_id,title=excluded.title,summary=excluded.summary,content=excluded.content,status='published',visibility='authenticated',availability='available',last_reviewed_at=now(),updated_at=now()
 returning id,slug,title,summary,content,current_version,availability,visibility
)
insert into public.knowledge_article_versions(article_id,version_number,title,summary,content,availability,visibility,change_summary)
select id,current_version,title,summary,content,availability,visibility,'Enrichissement du centre de documentation et de formation'
from upserted
on conflict(article_id,version_number) do update set title=excluded.title,summary=excluded.summary,content=excluded.content,availability=excluded.availability,visibility=excluded.visibility,change_summary=excluded.change_summary;

insert into public.knowledge_article_chunks(article_id,article_version,chunk_index,heading,content)
select article.id,article.current_version,0,article.title,article.content
from public.knowledge_articles article
where article.slug in('prise-en-main-piloz-15-minutes','cycle-vente-complet','checklist-avant-finalisation-facture','choisir-facture-acompte-situation','resoudre-erreur-synchronisation','checklist-export-comptable','securiser-equipe-et-droits','comprendre-statuts-facture-electronique')
on conflict(article_id,article_version,chunk_index) do update set heading=excluded.heading,content=excluded.content;

commit;
