begin;

insert into public.knowledge_categories(slug,name,description,position) values
('premiers-pas','Premiers pas','Découvrir Piloz et terminer la configuration initiale.',10),
('tableau-de-bord','Tableau de bord','Comprendre et personnaliser les indicateurs.',20),
('entreprise-parametres','Entreprise et paramètres','Configurer les informations de l’entreprise.',30),
('utilisateurs-roles','Utilisateurs et rôles','Gérer les accès et permissions.',40),
('crm-suivi-commercial','CRM et suivi commercial','Organiser le suivi commercial.',50),
('prospects','Prospects','Qualifier les futurs clients.',60),
('pipeline','Pipeline','Suivre les opportunités par étape.',70),
('opportunites','Opportunités','Centraliser une affaire commerciale.',80),
('activites','Activités','Planifier les actions et relances.',90),
('clients-contacts','Clients et contacts','Gérer le répertoire client.',100),
('articles-services','Articles et services','Configurer les éléments vendus.',110),
('devis','Devis','Créer, valider et suivre les devis.',120),
('factures','Factures','Créer, finaliser et suivre les factures.',130),
('avoirs','Avoirs','Corriger une facture finalisée.',140),
('reglements','Règlements','Enregistrer et affecter les paiements.',150),
('echeances-relances','Échéances et relances','Suivre le reste à payer et les relances.',160),
('facturation-electronique','Facturation électronique','Comprendre les fonctions et prérequis du connecteur.',170),
('achats','Achats','Gérer les commandes et documents fournisseurs.',180),
('fournisseurs','Fournisseurs','Gérer les tiers fournisseurs.',190),
('comptabilite','Comptabilité','Paramétrer et produire les écritures.',200),
('tva-encaissements','TVA sur encaissements','Préparer la TVA selon les règlements.',210),
('exports-comptables','Exports comptables','Prévisualiser, contrôler et exporter les journaux.',220),
('fichiers-stockage-documentaire','Fichiers et stockage documentaire','Gérer les justificatifs et archives.',230),
('extensions','Extensions','Connecter des services externes.',240),
('google-agenda','Google Agenda','Configurer l’agenda Google lorsqu’il est disponible.',250),
('outlook-calendar','Outlook Calendar','Configurer l’agenda Microsoft lorsqu’il est disponible.',260),
('gmail','Gmail','Configurer Gmail lorsqu’il est disponible.',270),
('outlook-mail','Outlook Mail','Configurer Outlook lorsqu’il est disponible.',280),
('securite','Sécurité','Protéger les comptes et les données.',290),
('abonnement','Abonnement','Consulter l’offre et la facturation Piloz.',300),
('faq','Questions fréquentes','Réponses rapides aux questions courantes.',310),
('resolution-erreurs','Résolution des erreurs','Diagnostiquer les erreurs sans perdre les données.',320),
('conformite','Conformité','Comprendre les contrôles et limites déclarées.',330),
('import-export-donnees','Import et export de données','Transférer des données de manière contrôlée.',340),
('roadmap','Roadmap et fonctionnalités à venir','Fonctionnalités annoncées sans promesse de date.',350)
on conflict(slug) do update set name=excluded.name,description=excluded.description,position=excluded.position,active=true,updated_at=now();

with source(category_slug,slug,title,summary,availability,prerequisites,steps,expected_result,special_cases,errors,limits) as (values
('premiers-pas','terminer-configuration-initiale','Terminer la configuration initiale','L’onboarding collecte les informations indispensables avant l’utilisation complète de Piloz.','available','Un compte actif, une licence associée et le rôle Propriétaire ou Administrateur.','Ouvrez Piloz après connexion. Complétez chaque étape affichée, contrôlez les informations puis validez. Les données sont enregistrées dans l’entreprise active.','Le tableau de bord s’ouvre et les paramètres saisis sont repris dans les documents concernés.','Une entreprise non assujettie à la TVA masque les réglages TVA inutiles.','Si une référence n’est plus valide, rechargez puis sélectionnez à nouveau la valeur proposée. Si vos droits sont insuffisants, contactez l’administrateur de l’entreprise.','Le menu peut être volontairement limité tant que l’onboarding n’est pas terminé.'),
('tableau-de-bord','personnaliser-tableau-de-bord','Personnaliser le tableau de bord','Les widgets affichent les données autorisées de l’entreprise et leur disposition est enregistrée par utilisateur.','available','La permission de consultation du tableau de bord ; la personnalisation dépend du rôle.','Ouvrez Tableau de bord, choisissez Personnaliser, activez les widgets utiles puis déplacez-les par glisser-déposer. Enregistrez la disposition.','La disposition est restaurée à la prochaine connexion de cet utilisateur.','Une période sans donnée affiche zéro ou un état vide, jamais des données fictives.','Si l’enregistrement échoue, conservez la page ouverte et réessayez après le retour de la connexion.','Les montants dépendent des documents et règlements réellement enregistrés.'),
('entreprise-parametres','configurer-entreprise','Configurer les informations de l’entreprise','Les coordonnées, informations légales, fiscales et bancaires alimentent les documents et contrôles métier.','available','Rôle Propriétaire ou Administrateur et permission Paramétrer l’entreprise.','Ouvrez Paramètres puis Mon entreprise. Complétez identité, coordonnées, adresses, fiscalité et banque. Enregistrez chaque section.','Les informations rechargées correspondent aux données enregistrées et sont utilisées par les modèles compatibles.','L’adresse du siège peut être copiée vers la facturation et la livraison.','Un champ obligatoire ou invalide est signalé avant sauvegarde.','Ne saisissez jamais de clé API ou de secret dans ces formulaires.'),
('utilisateurs-roles','gerer-utilisateurs-roles','Gérer les utilisateurs et les rôles','Piloz utilise un catalogue central de permissions et des rôles propres à chaque entreprise.','available','Permission Gérer les utilisateurs et droits d’accès.','Ouvrez Paramètres puis Équipe et accès. Invitez un utilisateur ou créez un rôle. Activez uniquement les permissions nécessaires et attribuez le rôle.','L’utilisateur voit seulement les modules et actions autorisés dans l’entreprise concernée.','Les rôles système peuvent servir de base à un rôle personnalisé.','Une invitation expirée doit être renvoyée ; une permission sensible peut nécessiter un administrateur.','Le principe du moindre privilège est recommandé. Les droits d’une autre entreprise ne sont jamais réutilisés.'),
('crm-suivi-commercial','comprendre-suivi-commercial','Comprendre le suivi commercial','Le suivi commercial réunit pipeline, opportunités, activités et relances dans un même espace.','available','Permissions CRM correspondant à la portée propre, équipe ou entreprise.','Ouvrez Suivi commercial puis choisissez Pipeline ou Activités. Utilisez les filtres pour retrouver les éléments autorisés.','Les modifications persistées sont visibles après actualisation.','Un commercial peut être limité à ses propres opportunités ou à celles de son équipe.','Si une page reste vide, vérifiez les filtres et les permissions avant de créer un doublon.','Les rapports respectent la même portée que les données sources.'),
('prospects','creer-qualifier-prospect','Créer et qualifier un prospect','Un prospect peut être créé avant de devenir client et relié aux opportunités et activités.','available','Permission de création de prospects.','Ouvrez Bibliothèque puis Prospects, lancez la création, recherchez l’entreprise si nécessaire, complétez le contact et enregistrez.','Le prospect apparaît dans la liste et peut être sélectionné dans une opportunité.','La création d’un devis pour ce tiers peut déclencher sa conversion en client selon le parcours utilisé.','Évitez de recréer un prospect déjà trouvé par la recherche.','La recherche officielle dépend de la disponibilité du service externe.'),
('pipeline','deplacer-opportunite-pipeline','Déplacer une opportunité dans le pipeline','Le pipeline affiche les opportunités par étape et enregistre les déplacements autorisés.','available','Permission de lecture du pipeline et d’écriture pour déplacer une opportunité.','Ouvrez Suivi commercial, choisissez Pipeline puis déplacez une carte vers une autre colonne.','La nouvelle étape est conservée après actualisation et les totaux sont recalculés.','Certaines automatisations peuvent modifier l’étape à la suite d’une action sur un devis ou une facture.','En cas de refus serveur, replacez la carte dans son étape précédente et vérifiez vos droits.','Les étapes disponibles dépendent du paramétrage de l’entreprise.'),
('opportunites','gerer-opportunite','Gérer une opportunité','Une opportunité centralise tiers, montant, étape, responsable, activités, notes et documents liés.','available','Permissions de consultation ou gestion des opportunités.','Ouvrez une opportunité depuis le pipeline. Complétez ses informations puis utilisez les actions pour ajouter une activité ou créer un document.','Les liens créés sont visibles dans l’opportunité et le document concerné.','Un devis existant doit être ouvert en consultation depuis le lien, pas modifié automatiquement.','Si un document lié est inaccessible, vérifiez les permissions de vente.','Une opportunité ne remplace pas le document comptable ou commercial.'),
('activites','planifier-activite-relance','Planifier une activité ou une relance','Les activités permettent de suivre appels, rendez-vous, tâches et prochaines actions commerciales.','available','Permission de création d’activités ou de relances.','Depuis Suivi commercial ou une opportunité, ajoutez une activité, choisissez son type, sa date et son responsable puis enregistrez.','L’activité apparaît dans la liste et reste reliée au contexte commercial.','Une activité terminée reste dans l’historique.','Une date invalide ou un responsable inaccessible bloque la sauvegarde.','Les notifications dépendent des préférences et services configurés.'),
('clients-contacts','creer-client-contact-principal','Créer un client et son contact principal','La création d’un client peut enregistrer simultanément ses coordonnées et un contact principal.','available','Permission de création de clients.','Ouvrez Bibliothèque puis Clients. Recherchez d’abord l’entreprise, sélectionnez le résultat ou saisissez les informations, puis complétez nom, prénom, e-mail et téléphone du contact.','La fiche client est créée et le contact principal apparaît dans l’onglet Contacts.','Un particulier ne nécessite pas les mêmes identifiants légaux qu’une société.','Vérifiez les doublons avant validation. Une recherche externe indisponible n’empêche pas une saisie manuelle autorisée.','Les données d’un client ne sont visibles que dans son entreprise Piloz.'),
('articles-services','creer-article-service','Créer un article ou un service','Le catalogue fournit les désignations, descriptions, unités, prix et types utilisés dans les documents.','available','Permission de gestion du catalogue.','Ouvrez Bibliothèque puis Articles et services. Choisissez le type, complétez la désignation, l’unité et les prix puis enregistrez.','L’élément peut être recherché dans un devis ou une facture.','Une ligne ponctuelle peut être saisie directement dans un document sans créer de fiche catalogue.','Un taux de TVA proposé dépend des taux configurés en comptabilité.','La gestion des stocks n’est pas incluse dans cette procédure.'),
('devis','creer-valider-devis','Créer et valider un devis','Un devis peut être conservé en brouillon puis validé lorsqu’il contient les informations nécessaires.','available','Permissions de création et de finalisation des devis ; client requis pour valider.','Ouvrez Ventes puis Devis, créez le document, sélectionnez le client, ajoutez les lignes et contrôlez les conditions. Enregistrez le brouillon ou validez après confirmation.','Le brouillon reste modifiable ; le devis validé reçoit son numéro définitif et s’ouvre en consultation.','Un devis déjà lié à une facture doit être corrigé par le parcours d’avoir et de duplication approprié.','Si la validation est grisée, vérifiez le client et les champs obligatoires.','Un brouillon ne doit pas être présenté comme un document définitif.'),
('devis','convertir-devis-facture','Convertir un devis en facture','La conversion reprend le client, les lignes et les liens du devis dans une facture brouillon.','available','Devis accessible et permission de conversion.','Depuis la consultation du devis, choisissez Convertir en facture. La facture brouillon s’ouvre pour contrôle. Activez Situation dans ses paramètres uniquement si nécessaire.','La facture brouillon et le devis sont liés sans ressaisie des lignes.','Si un acompte est prévu, le parcours peut imposer une facture d’acompte avant le solde.','Ne relancez pas la conversion si la facture liée existe déjà.','La facture reste un brouillon jusqu’à finalisation explicite.'),
('factures','creer-finaliser-facture','Créer et finaliser une facture','Une facture brouillon reste modifiable ; la finalisation attribue un numéro fiscal et verrouille les éléments concernés.','available','Permission de création et de finalisation, client valide, lignes cohérentes et fiscalité configurée.','Créez ou ouvrez le brouillon, contrôlez client, dates, lignes, TVA et échéance puis cliquez sur Finaliser. Confirmez dans la fenêtre de contrôle.','La facture finalisée s’ouvre en consultation avec son numéro unique.','La date ne peut pas rompre la chronologie des factures déjà finalisées.','Si un contrôle TVA, client ou chronologie échoue, corrigez le brouillon ; aucune finalisation n’est simulée.','Une facture finalisée se corrige par avoir, pas par modification directe.'),
('factures','factures-situation','Créer des factures de situation','Le mode Situation facture un avancement sans modifier les quantités contractuelles.','available','Facture brouillon issue d’un devis et permission de finalisation.','Dans les paramètres du brouillon, activez Situation. Renseignez l’avancement global, par titre ou par ligne puis finalisez. Depuis une situation finalisée, créez la suivante jusqu’au solde.','Chaque situation possède son propre numéro de facture et le cumul d’avancement reste traçable.','Toutes les lignes, y compris à zéro sur la situation, peuvent rester visibles sur le PDF. À 100 %, aucune situation supplémentaire ne doit être créée.','Un avancement inférieur au cumul précédent ou supérieur à 100 % est refusé.','Les quantités du marché restent inchangées ; seul le montant facturé suit l’avancement.'),
('avoirs','corriger-facture-avoir','Corriger une facture avec un avoir','Un avoir conserve la piste d’audit d’une correction après finalisation.','available','Facture finalisée accessible et permission de création d’avoirs.','Ouvrez la facture, choisissez Créer un avoir, contrôlez les lignes et finalisez le nouvel avoir.','La facture et l’avoir sont liés et les montants sont repris dans les suivis concernés.','Un avoir partiel ne corrige que les montants sélectionnés.','Ne supprimez jamais une facture finalisée pour corriger une erreur.','Les règles comptables et fiscales de l’entreprise restent applicables.'),
('reglements','enregistrer-reglement','Enregistrer un règlement','Un règlement réel peut être affecté à une ou plusieurs factures et reste traçable.','available','Permission de saisir des règlements et factures finalisées accessibles.','Ouvrez Comptabilité puis Règlements ou la fiche facture. Sélectionnez les factures, saisissez montant, date, mode et référence puis validez.','Le montant encaissé, le reste à payer et le statut des factures sont recalculés.','Un règlement multi-factures répartit le montant entre les factures sélectionnées.','Le total affecté ne doit pas dépasser le règlement ni les soldes autorisés.','Une erreur se corrige par annulation ou contre-écriture traçable.'),
('echeances-relances','suivre-echeances-relancer','Suivre les échéances et relancer un client','Les échéances utilisent les vraies dates et les règlements enregistrés.','available','Permission de lecture des échéances ; permission de relance pour enregistrer une action.','Ouvrez Ventes puis Échéances. Filtrez les montants dus, ouvrez la facture et préparez une relance.','La relance enregistrée apparaît dans l’historique de la facture.','Sans service e-mail configuré, Piloz propose le contenu et l’enregistrement manuel sans simuler un envoi.','Vérifiez le destinataire et le reste à payer avant toute relance.','Les couleurs sont des indicateurs et ne remplacent pas le statut comptable.'),
('facturation-electronique','comprendre-facturation-electronique','Comprendre la facturation électronique dans Piloz','Piloz prépare et échange certains formats via un connecteur externe lorsqu’il est configuré.','external_connector_required','Entreprise et client correctement identifiés, fiscalité cohérente et connecteur autorisé.','Ouvrez Extensions pour contrôler l’état du connecteur. Depuis une facture finalisée compatible, utilisez les actions électroniques disponibles et consultez le statut retourné.','Le statut affiché provient du connecteur réel ; un refus conserve son motif.','Les factures fournisseur reçues peuvent nécessiter une décision : approuver, litige ou refuser avec motif.','Corrigez les coordonnées, montants ou TVA indiqués par le retour du connecteur.','Piloz intègre une architecture technique préparée pour plusieurs exigences de facturation électronique. Certaines fonctions peuvent nécessiter une configuration, un connecteur externe ou une validation complémentaire avant utilisation en production.'),
('achats','gerer-commande-fournisseur','Gérer une commande fournisseur','Les commandes fournisseurs organisent les achats et leurs réceptions sans modifier les factures client.','partial','Permissions Achats et fournisseur existant.','Ouvrez Achats puis Commandes fournisseurs. Créez la commande, sélectionnez le fournisseur, ajoutez les lignes et enregistrez.','La commande reste consultable et les réceptions autorisées peuvent lui être rattachées.','Une réception partielle conserve les quantités restantes.','Vérifiez les droits si les actions d’achat ne sont pas proposées.','Certaines fonctions dépendent du paramétrage de l’entreprise.'),
('fournisseurs','creer-fournisseur','Créer un fournisseur','La bibliothèque fournisseurs centralise les coordonnées utilisées dans les achats.','available','Permission de création de fournisseurs.','Ouvrez Bibliothèque puis Fournisseurs, recherchez l’entreprise ou saisissez-la, complétez le contact puis enregistrez.','Le fournisseur devient sélectionnable dans les commandes et factures d’achat.','Un fournisseur peut avoir plusieurs contacts et adresses.','Vérifiez les doublons et identifiants avant création.','Les informations bancaires nécessitent une permission adaptée.'),
('comptabilite','configurer-comptabilite','Configurer la comptabilité','Le paramétrage définit journaux, comptes de tiers, comptes de vente, TVA et comptes financiers.','available','Permission Paramétrage comptable.','Ouvrez Comptabilité puis Paramétrage. Contrôlez chaque onglet, adaptez les comptes et enregistrez.','Les prochains exports utilisent la configuration enregistrée.','Les types Article, Service, Main d’œuvre, Abonnement et Frais peuvent utiliser des comptes distincts.','Un compte manquant bloque l’export avec un message explicite.','La comptabilité définitive est tenue dans le logiciel comptable destinataire.'),
('tva-encaissements','preparer-tva-encaissements','Préparer la TVA sur encaissements','Le module rapproche les règlements réels et les écritures concernées selon la configuration fiscale.','available','Entreprise configurée pour le régime concerné, règlements enregistrés et permission comptable.','Ouvrez Comptabilité puis TVA sur encaissements, choisissez la période, contrôlez les lignes et préparez le résultat.','Les montants correspondent aux règlements et affectations de la période.','Une annulation de règlement modifie le calcul de la période concernée.','Vérifiez la configuration fiscale si aucune ligne n’apparaît.','Piloz fournit une préparation ; la validation déclarative reste sous la responsabilité de l’entreprise et de son conseil.'),
('exports-comptables','generer-export-comptable','Prévisualiser et générer un export comptable','L’export regroupe les lignes par compte, ajoute client et TVA puis produit le format choisi.','available','Comptes, journal, exercice et factures finalisées correctement configurés.','Ouvrez Comptabilité puis Exports comptables. Choisissez la période, lancez la prévisualisation, contrôlez l’équilibre et validez l’export.','Le fichier téléchargé correspond aux lignes affichées dans la prévisualisation.','Le mode client individualisé place par défaut le compte normalisé dans CompteNum lorsque ce mode est configuré.','Un compte manquant, une écriture déséquilibrée ou une période vide est signalé sans faux résultat.','Le fichier doit être contrôlé avant import dans le logiciel comptable.'),
('fichiers-stockage-documentaire','gerer-fichiers-justificatifs','Gérer les fichiers et justificatifs','Les pièces jointes autorisées sont stockées dans un espace privé et liées à leur objet métier.','available','Permission sur l’objet et fichier conforme aux limites affichées.','Ouvrez la fiche concernée, ajoutez le fichier, attendez la confirmation réelle puis rechargez si nécessaire.','Le fichier apparaît uniquement pour les utilisateurs autorisés de l’entreprise.','Les tickets support acceptent au maximum 10 Mo par fichier et des formats contrôlés.','Un format, une taille ou une permission invalide bloque l’ajout.','Une URL signée expire et ne doit pas être partagée publiquement.'),
('extensions','configurer-extension','Configurer une extension','Les extensions relient Piloz à un service externe sans stocker de secret dans le navigateur.','configuration_required','Permission personnelle ou d’entreprise selon le service et compte externe compatible.','Ouvrez Paramètres puis Extensions, choisissez le service et suivez l’autorisation affichée.','L’état Connecté n’est affiché qu’après confirmation réelle du fournisseur.','Une connexion personnelle n’accorde pas automatiquement l’accès aux autres utilisateurs.','Un fournisseur désactivé ou mal configuré renvoie un état explicite.','Les fonctions disponibles dépendent des autorisations accordées au fournisseur.'),
('google-agenda','connecter-google-agenda','Connecter Google Agenda','La connexion Google Agenda nécessite l’activation du fournisseur et une autorisation OAuth valide.','configuration_required','Fournisseur Google activé pour Piloz et permission d’extension personnelle.','Ouvrez Paramètres puis Extensions et choisissez Google Agenda. Autorisez uniquement les accès nécessaires.','Le calendrier connecté apparaît avec un état confirmé.','Si Google est désactivé dans la configuration, Piloz l’indique sans prétendre connecter le compte.','Une erreur Unsupported provider signifie que le fournisseur doit être activé côté plateforme.','Les événements accessibles dépendent des droits Google accordés.'),
('outlook-calendar','connecter-outlook-calendar','Connecter Outlook Calendar','La connexion Microsoft Calendar nécessite l’activation du fournisseur et une autorisation OAuth valide.','configuration_required','Fournisseur Microsoft activé et permission d’extension personnelle.','Ouvrez Paramètres puis Extensions et choisissez Outlook Calendar. Terminez l’autorisation Microsoft.','L’état connecté apparaît seulement après validation du fournisseur.','Les politiques de l’organisation Microsoft peuvent bloquer le consentement.','Un fournisseur désactivé doit être configuré par l’équipe plateforme.','Piloz ne connaît jamais le mot de passe Microsoft.'),
('gmail','connecter-gmail','Connecter Gmail','Gmail peut être utilisé uniquement lorsque l’extension et les autorisations nécessaires sont configurées.','configuration_required','Fournisseur Google activé et permission d’extension.','Ouvrez Extensions, sélectionnez Gmail et suivez l’autorisation. Testez ensuite une action non sensible.','Les fonctions disponibles reflètent les autorisations réellement accordées.','Sans configuration, l’ouverture de l’application de messagerie peut rester disponible pour un envoi manuel.','Révoquez puis reconnectez si le jeton a expiré.','Aucun envoi réussi n’est simulé.'),
('outlook-mail','connecter-outlook-mail','Connecter Outlook Mail','Outlook Mail nécessite un fournisseur Microsoft activé et les autorisations appropriées.','configuration_required','Fournisseur Microsoft activé et permission d’extension.','Ouvrez Extensions, sélectionnez Outlook Mail et terminez l’autorisation.','L’état connecté est confirmé par le serveur.','Les restrictions Microsoft 365 de l’entreprise peuvent limiter le service.','Si l’autorisation est refusée, contactez l’administrateur Microsoft de votre organisation.','Aucun e-mail n’est envoyé sans confirmation du service.'),
('securite','proteger-compte-mfa','Protéger son compte et activer le MFA','Le MFA ajoute un second facteur et réduit le risque lié au mot de passe.','available','Compte actif et application d’authentification compatible.','Ouvrez Paramètres puis Sécurité, activez le MFA, scannez le code et confirmez le code temporaire. Conservez les moyens de récupération proposés.','Les prochaines connexions sensibles demandent le second facteur selon la politique.','Un administrateur plateforme peut réinitialiser un facteur après vérification appropriée, sans voir vos codes.','Une horloge de téléphone désynchronisée peut produire un code invalide.','Ne partagez jamais mot de passe, code MFA ou lien de connexion.'),
('abonnement','comprendre-abonnement','Comprendre l’abonnement Piloz','La page Abonnement affiche l’offre, le statut et les informations de facturation réellement enregistrées.','available','Permission de gestion de l’abonnement pour modifier l’offre.','Ouvrez Paramètres puis Abonnement et utilisation. Consultez le plan, l’essai, les limites et la facturation. Lancez un changement uniquement via le paiement proposé.','Le plan change uniquement après une opération serveur confirmée.','Une licence administrée manuellement doit être active et rattachée à l’entreprise.','Si le service de paiement est indisponible, aucun succès ne doit être affiché.','Les prix et dates contractuels restent ceux du contrat enregistré.'),
('faq','difference-brouillon-finalise','Quelle différence entre un brouillon et un document finalisé ?','Un brouillon est modifiable et provisoire ; un document finalisé reçoit un numéro définitif et suit les règles de verrouillage.','available','Aucun prérequis.','Utilisez le brouillon pour préparer et contrôler le document. Finalisez seulement lorsque client, lignes, dates et fiscalité sont corrects.','La consultation distingue clairement les deux états.','Un PDF de brouillon peut porter un filigrane provisoire.','Si la finalisation échoue, le brouillon doit rester modifiable.','Une facture finalisée se corrige par avoir.'),
('resolution-erreurs','document-non-enregistre','Le document n’a pas pu être enregistré','Piloz conserve autant que possible le formulaire et affiche une erreur compréhensible lorsqu’une création échoue.','available','Connexion active et droits sur le document.','Ne fermez pas immédiatement le formulaire. Lisez le message, vérifiez client, lignes, TVA et connexion, puis réessayez une seule fois.','Le document est créé une fois ou reste en brouillon sans double soumission.','Une réponse serveur vide ou non JSON doit être traitée sans effacer le formulaire.','Si l’erreur persiste, créez un ticket avec le module, l’action, l’heure et une capture sans donnée sensible.','Ne communiquez jamais de token, cookie ou clé dans un ticket.'),
('conformite','etat-conformite-piloz','Comprendre l’état de conformité de Piloz','Piloz fournit des contrôles, journaux et pistes d’audit sans revendiquer une certification non obtenue.','partial','Accès aux modules concernés et configuration correcte.','Consultez les états techniques et conservez les documents et justificatifs selon vos obligations. Faites valider les cas spécifiques par votre conseil.','Les contrôles indiquent leur résultat réel et les limites connues.','Les connecteurs externes et signatures peuvent nécessiter une configuration distincte.','Une anomalie doit être corrigée ; elle ne doit pas être masquée par une fausse validation.','Piloz n’est pas présenté comme certifié NF525, NF203 ou AFNOR.'),
('import-export-donnees','importer-exporter-donnees','Importer ou exporter des données','Les outils de transfert servent à reprendre ou restituer les données autorisées de l’entreprise.','partial','Permission de gestion des données et format compatible.','Depuis Paramètres, ouvrez l’outil concerné, sélectionnez le format, contrôlez l’aperçu puis confirmez.','Les données acceptées sont enregistrées ou un fichier réel est téléchargé.','Une reprise importante doit d’abord être testée sur un échantillon.','Les lignes invalides doivent être signalées sans écraser les données existantes.','Aucun import ne doit contourner les contrôles de société et de permission.'),
('roadmap','la-gestion-des-stocks-est-elle-disponible','La gestion des stocks est-elle disponible dans Piloz ?','État officiel de la fonctionnalité de gestion des stocks.','roadmap','','','','','',''),
('resolution-erreurs','creer-ticket-support','Créer un ticket utile pour le support','Un ticket précis accélère le diagnostic sans exposer de donnée sensible.','available','Permission de création de tickets.','Depuis Aide et support, choisissez Contacter le support. Sélectionnez type, catégorie, module et priorité, décrivez les étapes, vérifiez le contexte prérempli puis envoyez.','Un vrai numéro SUP est affiché et le ticket apparaît dans Mes tickets.','Une suggestion de stock est classée Fonctionnalité à venir, module Roadmap et priorité normale.','Si la création échoue, Piloz ne doit pas inventer de numéro. Conservez votre texte et réessayez.','Maximum 10 Mo par pièce jointe ; retirez mots de passe, coordonnées bancaires et secrets.'),
('facturation-electronique','traiter-facture-fournisseur-electronique','Traiter une facture fournisseur électronique','Une facture reçue par un connecteur reste en attente de décision jusqu’à une action réellement acceptée.','external_connector_required','Connecteur configuré, facture reçue et permission Achats.','Ouvrez Achats puis Factures fournisseurs. Sélectionnez la facture, contrôlez vendeur, acheteur, lignes et montants puis approuvez, signalez un litige ou refusez avec un motif obligatoire.','La décision et le motif sont transmis au connecteur et le statut change uniquement après acceptation.','Une facture en litige peut être réexaminée puis approuvée lorsque le litige est résolu et que le connecteur l’autorise.','Un statut Litige, Rejetée ou Refusée sans motif est refusé.','Les règles du connecteur et de la plateforme externe restent applicables.'),
('comptabilite','comptes-clients-individualises','Utiliser des comptes clients individualisés','Le mode individualisé inscrit 411 suivi de l’identifiant normalisé directement dans CompteNum.','available','Mode comptable client individualisé activé et fiches clients accessibles.','Dans Comptabilité puis Paramétrage des tiers, choisissez la longueur et le mode individualisé. Contrôlez l’exemple puis générez l’export.','SOLUNEO produit 411SOLUNEO dans CompteNum ; CompAuxNum et CompAuxLib restent vides.','L’identifiant est normalisé en majuscules sans espaces, accents ni caractères spéciaux et conservé dans la fiche client.','Un conflit d’identifiant doit être résolu avant export afin de garantir un compte stable.','Un autre mode n’est utilisé que s’il a été explicitement activé.'),
('fichiers-stockage-documentaire','archives-fiscales','Comprendre une archive fiscale Piloz','Une archive fiscale regroupe un manifeste JSON, les empreintes et, lorsque disponibles, les documents et justificatifs inclus par le moteur.','partial','Données fiscales existantes et permission de conformité.','Ouvrez l’espace d’archives, créez l’archive pour la période, vérifiez son statut puis téléchargez le paquet disponible.','Le téléchargement contient les éléments réellement inclus et leur manifeste de contrôle.','Une signature KMS n’est indiquée comme valide qu’après enregistrement confirmé dans le registre fiscal.','Un statut À signer ou une erreur de registre signifie que la signature n’est pas complète.','L’archive Piloz ne remplace pas les obligations de conservation et de contrôle propres à l’entreprise.')
), prepared as (
 select category.id as category_id,source.*,
 case when source.slug='la-gestion-des-stocks-est-elle-disponible' then
   'La gestion des stocks fait partie de la roadmap Piloz et n’est pas encore disponible dans la version actuelle. Sa disponibilité sera annoncée officiellement lors de sa mise en production.'
 else format(E'## Résumé\n\n%s\n\n## Disponibilité\n\n%s\n\n## Prérequis et permissions\n\n%s\n\n## Étapes\n\n%s\n\n## Résultat attendu\n\n%s\n\n## Cas particuliers\n\n%s\n\n## Erreurs et résolution\n\n%s\n\n## Avertissements et limites\n\n%s\n\n## Articles liés\n\nConsultez les autres articles de la même catégorie depuis le centre d’aide.\n\n## Mise à jour et version\n\nDernière revue : 29 juillet 2026. Compatible avec la version web actuelle de Piloz.',
  source.summary,
  case source.availability when 'available' then 'Disponible' when 'partial' then 'Partiellement disponible' when 'configuration_required' then 'Configuration requise' when 'external_connector_required' then 'Connecteur externe requis' when 'roadmap' then 'Roadmap' else source.availability end,
  source.prerequisites,source.steps,source.expected_result,source.special_cases,source.errors,source.limits)
 end as article_content
 from source join public.knowledge_categories category on category.slug=source.category_slug
)
insert into public.knowledge_articles(category_id,slug,title,summary,content,status,visibility,availability,current_version,published_at,last_reviewed_at)
select category_id,slug,title,summary,article_content,'published','authenticated',availability,1,now(),now() from prepared
on conflict(slug) do update set category_id=excluded.category_id,title=excluded.title,summary=excluded.summary,content=excluded.content,
 status='published',visibility='authenticated',availability=excluded.availability,published_at=coalesce(public.knowledge_articles.published_at,now()),last_reviewed_at=now(),updated_at=now();

insert into public.knowledge_article_versions(article_id,version_number,title,summary,content,availability,visibility,change_summary)
select id,current_version,title,summary,content,availability,visibility,'Publication initiale auditéée'
from public.knowledge_articles article
where article.slug in(
 select unnest(array[
 'terminer-configuration-initiale','personnaliser-tableau-de-bord','configurer-entreprise','gerer-utilisateurs-roles','comprendre-suivi-commercial',
 'creer-qualifier-prospect','deplacer-opportunite-pipeline','gerer-opportunite','planifier-activite-relance','creer-client-contact-principal',
 'creer-article-service','creer-valider-devis','convertir-devis-facture','creer-finaliser-facture','factures-situation','corriger-facture-avoir',
 'enregistrer-reglement','suivre-echeances-relancer','comprendre-facturation-electronique','gerer-commande-fournisseur','creer-fournisseur',
 'configurer-comptabilite','preparer-tva-encaissements','generer-export-comptable','gerer-fichiers-justificatifs','configurer-extension',
 'connecter-google-agenda','connecter-outlook-calendar','connecter-gmail','connecter-outlook-mail','proteger-compte-mfa','comprendre-abonnement',
 'difference-brouillon-finalise','document-non-enregistre','etat-conformite-piloz','importer-exporter-donnees',
 'la-gestion-des-stocks-est-elle-disponible','creer-ticket-support','traiter-facture-fournisseur-electronique','comptes-clients-individualises','archives-fiscales'
 ]::text[])
)
on conflict(article_id,version_number) do update set title=excluded.title,summary=excluded.summary,content=excluded.content,availability=excluded.availability,visibility=excluded.visibility,change_summary=excluded.change_summary;

insert into public.knowledge_article_chunks(article_id,article_version,chunk_index,heading,content)
select article.id,article.current_version,0,article.title,article.content
from public.knowledge_articles article where article.status='published'
on conflict(article_id,article_version,chunk_index) do update set heading=excluded.heading,content=excluded.content;

insert into public.knowledge_index_events(article_id,article_version,event_type,status,detail,completed_at)
select article.id,article.current_version,'publish','completed','Index textuel officiel initialisé',now()
from public.knowledge_articles article
where article.status='published' and not exists(
 select 1 from public.knowledge_index_events event where event.article_id=article.id and event.article_version=article.current_version and event.event_type='publish' and event.status='completed'
);

commit;
