begin;

-- Corpus officiel prudent consacré à la facturation électronique. Ces articles
-- décrivent uniquement les capacités observables et ne revendiquent aucune
-- certification ni qualité de plateforme agréée pour Piloz.
with source(slug,title,summary,availability,guidance,limits) as (values
('difference-pdf-facture-electronique','Différence entre facture PDF et facture électronique','Un PDF lisible ne suffit pas toujours à constituer une facture électronique structurée.','available','Une facture électronique contient des données structurées exploitables par les systèmes concernés. Factur-X associe par exemple une représentation PDF et un fichier XML conforme au profil utilisé.','La conformité dépend du format, des données, du circuit de transmission et des contrôles réellement appliqués.'),
('comprendre-factur-x','Comprendre Factur-X','Factur-X associe un PDF lisible et des données XML structurées.','external_connector_required','Piloz peut préparer ce format lorsque le document est finalisé, complet et qu’un connecteur compatible est configuré. Le PDF et les données doivent décrire la même facture.','Une conversion refusée doit être corrigée ; elle ne doit jamais être présentée comme réussie.'),
('comprendre-ubl','Comprendre UBL','UBL est un format XML structuré utilisé pour échanger des documents électroniques.','external_connector_required','Les champs émetteur, destinataire, lignes, TVA, totaux et références doivent être traduits dans la structure UBL attendue par le destinataire ou le connecteur.','La disponibilité d’un export UBL ne prouve pas à elle seule qu’une transmission réglementaire a abouti.'),
('comprendre-cii','Comprendre CII','CII est un modèle XML structuré utilisé pour représenter une facture électronique.','external_connector_required','Piloz ne propose une action CII que lorsque le connecteur et le document sont compatibles. Le résultat du contrôle externe doit être conservé.','Un fichier techniquement généré peut encore être rejeté si une donnée métier obligatoire manque.'),
('statuts-facturation-electronique','Comprendre les statuts de facturation électronique','Les statuts décrivent le traitement réel d’une facture par le circuit électronique.','external_connector_required','Consultez le statut depuis la facture ou la facture fournisseur. Un changement n’est affiché qu’après une réponse confirmée du connecteur. Les statuts de litige, refus ou rejet doivent conserver leur motif.','Les libellés disponibles dépendent du connecteur et du type de flux.'),
('preparer-entreprise-facturation-electronique','Préparer son entreprise à la facturation électronique','Une identité complète et cohérente réduit les rejets de factures électroniques.','available','Vérifiez raison sociale, SIREN ou SIRET, numéro de TVA lorsqu’il est requis, adresse, pays, e-mail, régime fiscal et paramètres de numérotation.','La validation finale des obligations propres à l’entreprise relève de l’entreprise et de ses conseils.'),
('verifier-informations-entreprise-electronique','Vérifier les informations obligatoires de l’entreprise','Le vendeur doit être identifié sans ambiguïté dans le document et le flux structuré.','available','Dans Paramètres, contrôlez l’identité légale, les coordonnées, les adresses, les identifiants et la fiscalité. Corrigez les données avant de finaliser la facture.','Une valeur inventée pour contourner un contrôle rendrait le document incohérent et ne doit jamais être utilisée.'),
('verifier-informations-client-electronique','Vérifier les informations du client','Le destinataire doit disposer des identifiants et coordonnées adaptés au flux.','available','Ouvrez la fiche client et contrôlez nom légal, adresse, pays, identifiants d’entreprise et numéro de TVA lorsqu’il est applicable. Utilisez la recherche officielle disponible pour éviter les erreurs de saisie.','Certaines opérations B2C ou internationales suivent des règles différentes.'),
('mentions-obligatoires-facture-electronique','Vérifier les mentions obligatoires d’une facture','La facture doit être complète avant conversion ou transmission électronique.','available','Contrôlez numéro, dates, vendeur, client, lignes, quantités, prix, TVA, totaux, échéance, conditions, pénalités et indemnité lorsque ces mentions s’appliquent. Piloz vérifie les informations connues avant la finalisation.','Les contrôles Piloz ne remplacent pas un avis fiscal ou juridique adapté au cas particulier.'),
('flux-b2b-facturation-electronique','Comprendre les flux B2B','Un flux B2B relie deux entreprises identifiées et peut nécessiter un routage par annuaire.','external_connector_required','Vérifiez les identifiants des deux entreprises puis suivez le statut transmis par le connecteur. Une facture sans destinataire électronique identifiable ne doit pas être annoncée comme distribuée.','Le calendrier et les obligations applicables doivent être vérifiés auprès des sources officielles à jour.'),
('flux-b2c-facturation-electronique','Comprendre les flux B2C','Les ventes à des particuliers ne suivent pas toujours le même circuit que les échanges B2B.','partial','Identifiez correctement le client et la nature de l’opération. Les données nécessaires à l’e-reporting peuvent différer des données de transmission B2B.','Piloz ne doit pas transformer automatiquement un flux B2C en flux B2B.'),
('operations-internationales-facturation-electronique','Comprendre les opérations internationales','Le pays, la devise, la TVA et le type de client influencent le traitement électronique.','partial','Contrôlez les adresses, identifiants fiscaux, devise, règles de TVA et nature de l’opération avant finalisation.','Une règle française ne doit pas être appliquée sans contrôle à une opération internationale.'),
('comprendre-e-reporting','Comprendre l’e-reporting','L’e-reporting concerne la transmission de certaines données qui ne suivent pas le flux standard de facture électronique.','external_connector_required','Conservez des données complètes sur l’opération et utilisez uniquement une fonction réellement connectée et confirmée par le prestataire.','Piloz ne présente aucune transmission comme réussie sans accusé réel du connecteur.'),
('role-plateformes-agreees','Comprendre le rôle des plateformes agréées','Une plateforme agréée assure des fonctions réglementées de transmission et de suivi.','available','Piloz peut dialoguer avec un connecteur externe lorsqu’il est configuré. Vérifiez le statut officiel du prestataire choisi et les conditions de son offre.','Piloz n’est pas présenté comme une plateforme agréée.'),
('role-annuaire-facturation-electronique','Comprendre le rôle de l’annuaire','L’annuaire permet d’identifier l’adresse de réception électronique d’une entreprise.','external_connector_required','L’identifiant électronique doit être obtenu ou confirmé par le service connecté. Une simple adresse postale ou e-mail ne remplace pas nécessairement cette information.','L’annuaire et ses données sont gérés par le circuit externe concerné.'),
('circuit-facture-electronique','Comprendre le circuit d’une facture électronique','Le circuit va de la finalisation du document à sa préparation, son contrôle, sa transmission et son suivi.','external_connector_required','Finalisez la facture, vérifiez les données structurées, envoyez-la via le connecteur configuré puis suivez chaque statut et motif retourné.','Une préparation locale n’est pas une preuve de remise au destinataire.'),
('erreurs-validation-facture-electronique','Comprendre les erreurs de validation','Une erreur de validation signale une donnée absente, incohérente ou non conforme au format attendu.','external_connector_required','Lisez le motif complet, corrigez le brouillon lorsque cela est encore possible ou utilisez l’avoir et un nouveau document si la facture est finalisée. Relancez ensuite un seul envoi contrôlé.','Ne modifiez jamais directement une facture finalisée.'),
('corriger-facture-electronique-rejetee','Corriger une facture rejetée','Un rejet doit conserver son motif et être traité sans effacer la piste d’audit.','external_connector_required','Consultez le motif, vérifiez les données du vendeur et du client, puis appliquez le parcours de correction autorisé. Renvoyez seulement après correction réelle.','Le statut ne doit pas être forcé manuellement pour masquer un rejet externe.'),
('suivre-statut-facture-electronique','Suivre le statut d’une facture électronique','Le suivi permet de connaître le dernier état réellement retourné par le connecteur.','external_connector_required','Ouvrez la facture et consultez l’historique électronique. Rafraîchissez ou synchronisez si l’action est proposée, puis contrôlez la date et le motif.','Une absence de retour doit rester visible comme telle ; Piloz ne simule pas une acceptation.'),
('archiver-facture-electronique','Archiver une facture électronique','L’archive doit préserver le document, les données structurées et les preuves disponibles.','partial','Conservez le PDF original, le XML, les statuts, motifs et justificatifs associés selon les durées applicables. Utilisez les archives Piloz uniquement pour les éléments réellement inclus.','Une archive JSON seule n’inclut pas automatiquement les PDF si le paquet ne les contient pas.'),
('connecteurs-facturation-electronique','Comprendre les connecteurs nécessaires','Les échanges électroniques nécessitent un service externe configuré côté serveur.','external_connector_required','Activez le connecteur dans Extensions, complétez les identifiants de l’entreprise et testez les flux autorisés avant la production. Les secrets restent côté serveur.','L’interface ne doit jamais exposer de secret ou prétendre qu’un connecteur est actif sans vérification.'),
('limites-actuelles-facturation-electronique','Comprendre les limites actuelles de Piloz','Les fonctions disponibles dépendent du document, de la configuration et du connecteur externe.','partial','Consultez l’état affiché dans Extensions et les actions proposées sur le document. En cas d’indisponibilité, conservez le brouillon ou utilisez le parcours réglementaire validé avec votre prestataire.','Piloz intègre une architecture technique préparée pour plusieurs exigences de facturation électronique. Certaines fonctions peuvent nécessiter une configuration, un connecteur externe ou une validation complémentaire avant utilisation en production.'),
('piloz-est-il-certifie','Piloz est-il certifié ?','Piloz ne revendique pas une certification qu’il n’a pas officiellement obtenue.','available','Consultez uniquement les déclarations et documents officiels publiés par Piloz. Les contrôles techniques intégrés restent distincts d’une certification délivrée par un organisme compétent.','Piloz n’est pas présenté comme certifié NF525, NF203 ou AFNOR.'),
('piloz-est-il-plateforme-agreee','Piloz est-il une plateforme agréée ?','Piloz n’est pas présenté comme une plateforme agréée.','available','Piloz peut utiliser un connecteur externe lorsqu’il est configuré. Vérifiez le statut officiel et le contrat du prestataire connecté.','Une intégration technique ou un bac à sable ne transforme pas Piloz en plateforme agréée.'),
('piloz-pret-pour-reforme','Piloz est-il prêt pour la réforme ?','Piloz comporte une architecture préparée, avec des fonctions qui dépendent encore de la configuration et de services externes.','partial','Vérifiez les informations légales, la qualité des factures, la configuration du connecteur et le résultat des tests applicables à votre entreprise.','Aucune garantie générale de conformité ne remplace la validation du parcours de production réellement utilisé.'),
('fonctions-electroniques-disponibles-a-activer','Comprendre les fonctionnalités disponibles et celles restant à activer','Piloz distingue les fonctions disponibles, partielles, à configurer et dépendantes d’un connecteur.','partial','Le centre d’aide affiche l’état de disponibilité de chaque article. L’interface doit proposer uniquement les actions autorisées et réellement configurées.','Une fonction marquée Configuration requise ou Connecteur externe requis ne doit pas être interprétée comme active en production.')
), prepared as (
 select category.id category_id,source.*,
 format(E'## Résumé\n\n%s\n\n## Disponibilité\n\n%s\n\n## Prérequis et permissions\n\nAccès au document ou aux paramètres concernés, informations d’entreprise autorisées et permission correspondant à l’action.\n\n## Explication et étapes\n\n%s\n\n## Résultat attendu\n\nPiloz affiche uniquement un résultat confirmé par ses données ou par le connecteur configuré.\n\n## Erreurs et résolution\n\nConsultez le motif affiché, corrigez les données à la source et réessayez sans dupliquer l’opération. Si le motif reste imprécis, créez un ticket avec le numéro du document et sans secret.\n\n## Avertissements et limites\n\n%s\n\n## Articles associés\n\nConsultez les autres articles de la catégorie Facturation électronique.\n\n## Mise à jour et version\n\nDernière revue : 29 juillet 2026. Compatible avec la version web actuelle de Piloz.',
 source.summary,
 case source.availability when 'available' then 'Disponible' when 'partial' then 'Partiellement disponible' when 'configuration_required' then 'Configuration requise' when 'external_connector_required' then 'Connecteur externe requis' else source.availability end,
 source.guidance,source.limits) content
 from source join public.knowledge_categories category on category.slug='facturation-electronique'
), upserted as (
 insert into public.knowledge_articles(category_id,slug,title,summary,content,status,visibility,availability,current_version,published_at,last_reviewed_at)
 select category_id,slug,title,summary,content,'published','authenticated',availability,1,now(),now() from prepared
 on conflict(slug) do update set category_id=excluded.category_id,title=excluded.title,summary=excluded.summary,content=excluded.content,status='published',visibility='authenticated',availability=excluded.availability,published_at=coalesce(public.knowledge_articles.published_at,now()),last_reviewed_at=now(),updated_at=now()
 returning id
)
select count(*) from upserted;

insert into public.knowledge_article_versions(article_id,version_number,title,summary,content,availability,visibility,change_summary)
select id,current_version,title,summary,content,availability,visibility,'Publication officielle facturation électronique'
from public.knowledge_articles article
where article.category_id=(select id from public.knowledge_categories where slug='facturation-electronique')
on conflict(article_id,version_number) do update set title=excluded.title,summary=excluded.summary,content=excluded.content,availability=excluded.availability,visibility=excluded.visibility,change_summary=excluded.change_summary;

insert into public.knowledge_article_chunks(article_id,article_version,chunk_index,heading,content)
select article.id,article.current_version,0,article.title,article.content
from public.knowledge_articles article
where article.category_id=(select id from public.knowledge_categories where slug='facturation-electronique') and article.status='published'
on conflict(article_id,article_version,chunk_index) do update set heading=excluded.heading,content=excluded.content;

insert into public.knowledge_index_events(article_id,article_version,event_type,status,detail,completed_at)
select article.id,article.current_version,'publish','completed','Index textuel officiel facturation électronique',now()
from public.knowledge_articles article
where article.category_id=(select id from public.knowledge_categories where slug='facturation-electronique') and article.status='published'
and not exists(select 1 from public.knowledge_index_events event where event.article_id=article.id and event.article_version=article.current_version and event.event_type='publish' and event.status='completed');

commit;
